# Getting data from reuters

In [1]:
from reuterspy import Reuters
reuters = Reuters()
import pandas as pd
pd.set_option('display.max_rows', None)

### Method for reshaping reuters data

In [2]:
def reshape_reuters_statements(df):
    return df.pivot(index="metric", columns="year", values="value").reset_index()

In [3]:
def get_metric_latest_bs(df, metric_name):
    return int(float(df[2020][df['metric'] == metric_name].iloc[0]))

# Selecting data

In [4]:
ticker_list = ['ABB.N']

## Get cash flow

In [5]:
df_cf = reuters.get_cash_flow(ticker_list)
df_cf = reshape_reuters_statements(df_cf)

KeyError: 'metric'

In [6]:
df_cf

year,metric,2015,2016,2017,2018,2019,2020
0,Capital Expenditures,-876.000000,-632.000000,-752.000000,-772.000000,-762.000000,-694.000000
1,Cash Interest Paid,221.000000,213.000000,205.000000,243.000000,284.000000,189.000000
2,Cash Taxes Paid,1043.000000,814.000000,894.000000,1026.000000,1005.000000,905.000000
3,Cash from Financing Activities,-3380.000000,-3355.000000,-1735.000000,-789.000000,-1383.000000,-8175.000000
4,Cash from Investing Activities,-974.000000,-1305.000000,-1450.000000,-3085.000000,-815.000000,6760.000000
5,Cash from Operating Activities,3818.000000,3843.000000,3799.000000,2924.000000,2325.000000,1693.000000
6,Changes in Working Capital,658.000000,528.000000,639.000000,50.000000,-372.000000,402.000000
7,Deferred Taxes,-219.000000,-145.000000,-199.000000,-142.000000,-83.000000,-280.000000
8,Depreciation/Depletion,1160.000000,870.000000,836.000000,916.000000,961.000000,915.000000
9,Financing Cash Flow Items,-613.000000,-1773.000000,-136.000000,-169.000000,-132.000000,-100.000000
10,Foreign Exchange Effects,-342.000000,-104.000000,268.000000,-131.000000,-28.000000,79.000000
11,"Issuance (Retirement) of Debt, Net",-30.000000,-475.000000,124.000000,1305.000000,414.000000,-3703.000000
12,"Issuance (Retirement) of Stock, Net",-1380.000000,-1107.000000,-88.000000,-208.000000,10.000000,-2636.000000
13,Net Change in Cash,-878.000000,-921.000000,882.000000,-1081.000000,99.000000,357.000000
14,Net Income/Starting Line,2055.000000,2034.000000,2365.000000,2298.000000,1528.000000,5205.000000
15,Non-Cash Items,164.000000,556.000000,158.000000,-198.000000,291.000000,-4549.000000
16,"Other Investing Cash Flow Items, Total",-98.000000,-673.000000,-698.000000,-2313.000000,-53.000000,7454.000000
17,Total Cash Dividends Paid,-1357.000000,0.000000,-1635.000000,-1717.000000,-1675.000000,-1736.000000

## Get balancesheet data

In [6]:
df_bs = reuters.get_balance_sheet(ticker_list)
df_bs = reshape_reuters_statements(df_bs)

KeyError: 'metric'

In [8]:
df_bs

year,metric,2015,2016,2017,2018,2019,2020
0,Accounts Payable,4342.000000,4446.000000,3736.000000,4424.000000,4353.000000,4571.000000
1,"Accounts Receivable - Trade, Net",10324.000000,10037.000000,6492.000000,6833.000000,6764.000000,7045.000000
2,Accrued Expenses,NaN,2641.000000,2433.000000,2735.000000,2942.000000,3061.000000
3,"Accumulated Depreciation, Total",-6840.000000,-6926.000000,-5547.000000,-5528.000000,-5716.000000,-6364.000000
4,Additional Paid-In Capital,1175.000000,24.000000,29.000000,56.000000,73.000000,83.000000
5,Capital Lease Obligations,NaN,NaN,NaN,NaN,154.000000,160.000000
6,Cash,1837.000000,1704.000000,1963.000000,1983.000000,2111.000000,1765.000000
7,Cash & Equivalents,2717.000000,1940.000000,2563.000000,1462.000000,1433.000000,1513.000000
8,Cash and Short Term Investments,6466.000000,5853.000000,5789.000000,4297.000000,4219.000000,5678.000000
9,"Common Stock, Total",269.000000,192.000000,188.000000,188.000000,188.000000,188.000000
10,Current Port. of LT Debt/Capital Leases,1176.000000,868.000000,409.000000,1470.000000,1449.000000,1140.000000
11,Deferred Income Tax,965.000000,918.000000,1050.000000,927.000000,911.000000,661.000000
12,"Goodwill, Net",9671.000000,9501.000000,9536.000000,10764.000000,10825.000000,10850.000000
13,"Intangibles, Net",2337.000000,1996.000000,2425.000000,2607.000000,2252.000000,2078.000000
14,Long Term Debt,5985.000000,5800.000000,6682.000000,6587.000000,6618.000000,4668.000000
15,Long Term Investments,263.000000,282.000000,279.000000,112.000000,51.000000,1808.000000
16,Minority Interest,507.000000,502.000000,530.000000,582.000000,454.000000,314.000000
17,Note Receivable - Long Term,NaN,112.000000,108.000000,30.000000,30.000000,NaN
18,Notes Payable/Short Term Debt,278.000000,135.000000,317.000000,561.000000,838.000000,153.000000
19,"Other Current Assets, Total",1251.000000,980.000000,5448.000000,5640.000000,10405.000000,1073.000000
20,"Other Current liabilities, Total",10048.000000,7059.000000,9574.000000,9257.000000,10684.000000,6491.000000
21,"Other Equity, Total",-4865.000000,-5194.000000,-4353.000000,-5307.000000,-5600.000000,-4019.000000
22,"Other Liabilities, Total",3574.000000,3438.000000,3908.000000,3946.000000,4179.000000,4184.000000
23,"Other Long Term Assets, Total",1049.000000,1516.000000,5171.000000,4930.000000,1526.000000,1983.000000
24,Prepaid Expenses,225.000000,176.000000,159.000000,176.000000,191.000000,201.000000
25,"Property/Plant/Equipment, Total - Gross",12116.000000,11669.000000,9351.000000,9661.000000,10682.000000,11507.000000
26,"Property/Plant/Equipment, Total - Net",5276.000000,4743.000000,3804.000000,4133.000000,4966.000000,5143.000000
27,Retained Earnings (Accumulated Deficit),20476.000000,19925.000000,19594.000000,19839.000000,19640.000000,22946.000000
28,Short Term Investments,1912.000000,2209.000000,1263.000000,852.000000,675.000000,2400.000000
29,"Tangible Book Value per Share, Common Eq",1.128390,0.887450,1.336380,0.272520,0.210450,1.357570
30,Total Assets,41356.000000,39202.000000,43458.000000,44441.000000,46108.000000,41088.000000
31,Total Common Shares Outstanding,2191.625140,2138.706840,2138.606490,2131.962410,2133.501110,2030.834170
32,Total Current Assets,22760.000000,21052.000000,22135.000000,21865.000000,26458.000000,19226.000000
33,Total Current Liabilities,15844.000000,15149.000000,16469.000000,18447.000000,20266.000000,15416.000000
34,Total Debt,7439.000000,6803.000000,7408.000000,8618.000000,9059.000000,6121.000000
35,Total Equity,14481.000000,13395.000000,14819.000000,13952.000000,13526.000000,15685.000000
36,Total Inventory,4757.000000,4347.000000,3737.000000,4284.000000,4184.000000,4469.000000
37,Total Liabilities,26875.000000,25807.000000,28639.000000,30489.000000,32582.000000,25403.000000
38,Total Liabilities & Shareholders' Equity,41356.000000,39202.000000,43458.000000,44441.000000,46108.000000,41088.000000
39,Total Long Term Debt,5985.000000,5800.000000,6682.000000,6587.000000,6772.000000,4828.000000
40,"Total Receivables, Net",10061.000000,9696.000000,7002.000000,7468.000000,7459.000000,7805.000000
41,Treasury Stock - Common,-2581.000000,-1559.000000,-647.000000,-820.000000,-785.000000,-3530.000000
42,Unrealized Gain (Loss),7.000000,7.000000,8.000000,-4.000000,10.000000,17.000000

## Income statement

In [9]:
df_is = reuters.get_income_statement(ticker_list)
df_is = reshape_reuters_statements(df_is)
df_is

year,metric,2015,2016,2017,2018,2019,2020
0,"Cost of Revenue, Total",25347.000000,17384.000000,17184.000000,19059.000000,19018.000000,18123.000000
1,DPS - Common Stock Primary Issue,0.740000,0.750580,0.762580,0.805990,0.786310,0.825210
2,Diluted EPS Excluding ExtraOrd Items,0.865470,0.510680,0.634540,0.677890,0.488520,0.138740
3,Diluted Net Income,1933.000000,1899.000000,2213.000000,2173.000000,1439.000000,5146.000000
4,Diluted Normalized EPS,1.153190,0.650030,0.706690,0.787000,0.633570,0.376870
5,Diluted Weighted Average Shares,2230.000000,2154.000000,2148.000000,2139.000000,2135.000000,2119.000000
6,Dilution Adjustment,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,Gross Profit,10134.000000,7545.000000,8012.000000,8603.000000,8960.000000,8011.000000
8,Income Available to Com Excl ExtraOrd,1930.000000,1100.000000,1363.000000,1450.000000,1043.000000,294.000000
9,Income Available to Com Incl ExtraOrd,1933.000000,1899.000000,2213.000000,2173.000000,1439.000000,5146.000000
10,"Interest Exp.(Inc.),Net-Operating, Total",-2.000000,-38.000000,69.000000,-52.000000,-33.000000,8.000000
11,"Interest Inc.(Exp.),Net-Non-Op., Total",-209.000000,-130.000000,-161.000000,-190.000000,-148.000000,-189.000000
12,Minority Interest,-122.000000,-135.000000,-152.000000,-125.000000,-47.000000,-51.000000
13,Net Income,1933.000000,1899.000000,2213.000000,2173.000000,1439.000000,5146.000000
14,Net Income After Taxes,2052.000000,1235.000000,1515.000000,1575.000000,1090.000000,345.000000
15,Net Income Before Extra. Items,1930.000000,1100.000000,1363.000000,1450.000000,1043.000000,294.000000
16,Net Income Before Taxes,2840.000000,1761.000000,2102.000000,2119.000000,1862.000000,841.000000
17,Operating Income,3049.000000,1929.000000,2230.000000,2226.000000,1938.000000,1431.000000
18,"Other Operating Expenses, Total",NaN,NaN,NaN,NaN,392.000000,-116.000000
19,"Other, Net",NaN,-38.000000,33.000000,83.000000,72.000000,-401.000000
20,Provision for Income Taxes,788.000000,526.000000,587.000000,544.000000,772.000000,496.000000
21,Research & Development,1406.000000,956.000000,1013.000000,1141.000000,1198.000000,1111.000000
22,Revenue,35481.000000,24929.000000,25196.000000,27662.000000,27978.000000,26134.000000
23,"Selling/General/Admin. Expenses, Total",5587.000000,4534.000000,4735.000000,5232.000000,5399.000000,4797.000000
24,Total Extraordinary Items,3.000000,799.000000,850.000000,723.000000,396.000000,4852.000000
25,Total Operating Expense,32432.000000,23000.000000,22966.000000,25436.000000,26040.000000,24703.000000
26,Total Revenue,35481.000000,24929.000000,25196.000000,27662.000000,27978.000000,26134.000000
27,Unusual Expense (Income),94.000000,164.000000,-35.000000,56.000000,66.000000,780.000000

### EBIT = Revenue − COGS − Operating Expenses

* [Kaavan lähde](https://www.investopedia.com/terms/e/ebit.asp)
==> Revenue - Cost of Revenue, Total - Total Operating Expense

In [10]:
df_is_orig = reuters.get_income_statement(ticker_list)
df_is_orig

,ticker,financialReport,year,metric,value
0,ABB.N,income_statement,2020,Revenue,26134.000000
1,ABB.N,income_statement,2019,Revenue,27978.000000
2,ABB.N,income_statement,2018,Revenue,27662.000000
3,ABB.N,income_statement,2017,Revenue,25196.000000
4,ABB.N,income_statement,2016,Revenue,24929.000000
5,ABB.N,income_statement,2015,Revenue,35481.000000
6,ABB.N,income_statement,2020,Total Revenue,26134.000000
7,ABB.N,income_statement,2019,Total Revenue,27978.000000
8,ABB.N,income_statement,2018,Total Revenue,27662.000000
9,ABB.N,income_statement,2017,Total Revenue,25196.000000
10,ABB.N,income_statement,2016,Total Revenue,24929.000000
11,ABB.N,income_statement,2015,Total Revenue,35481.000000
12,ABB.N,income_statement,2020,"Cost of Revenue, Total",18123.000000
13,ABB.N,income_statement,2019,"Cost of Revenue, Total",19018.000000
14,ABB.N,income_statement,2018,"Cost of Revenue, Total",19059.000000
15,ABB.N,income_statement,2017,"Cost of Revenue, Total",17184.000000
16,ABB.N,income_statement,2016,"Cost of Revenue, Total",17384.000000
17,ABB.N,income_statement,2015,"Cost of Revenue, Total",25347.000000
18,ABB.N,income_statement,2020,Gross Profit,8011.000000
19,ABB.N,income_statement,2019,Gross Profit,8960.000000
20,ABB.N,income_statement,2018,Gross Profit,8603.000000
21,ABB.N,income_statement,2017,Gross Profit,8012.000000
22,ABB.N,income_statement,2016,Gross Profit,7545.000000
23,ABB.N,income_statement,2015,Gross Profit,10134.000000
24,ABB.N,income_statement,2020,"Selling/General/Admin. Expenses, Total",4797.000000
25,ABB.N,income_statement,2019,"Selling/General/Admin. Expenses, Total",5399.000000
26,ABB.N,income_statement,2018,"Selling/General/Admin. Expenses, Total",5232.000000
27,ABB.N,income_statement,2017,"Selling/General/Admin. Expenses, Total",4735.000000
28,ABB.N,income_statement,2016,"Selling/General/Admin. Expenses, Total",4534.000000
29,ABB.N,income_statement,2015,"Selling/General/Admin. Expenses, Total",5587.000000
30,ABB.N,income_statement,2020,Research & Development,1111.000000
31,ABB.N,income_statement,2019,Research & Development,1198.000000
32,ABB.N,income_statement,2018,Research & Development,1141.000000
33,ABB.N,income_statement,2017,Research & Development,1013.000000
34,ABB.N,income_statement,2016,Research & Development,956.000000
35,ABB.N,income_statement,2015,Research & Development,1406.000000
36,ABB.N,income_statement,2020,"Interest Exp.(Inc.),Net-Operating, Total",8.000000
37,ABB.N,income_statement,2019,"Interest Exp.(Inc.),Net-Operating, Total",-33.000000
38,ABB.N,income_statement,2018,"Interest Exp.(Inc.),Net-Operating, Total",-52.000000
39,ABB.N,income_statement,2017,"Interest Exp.(Inc.),Net-Operating, Total",69.000000
40,ABB.N,income_statement,2016,"Interest Exp.(Inc.),Net-Operating, Total",-38.000000
41,ABB.N,income_statement,2015,"Interest Exp.(Inc.),Net-Operating, Total",-2.000000
42,ABB.N,income_statement,2020,Unusual Expense (Income),780.000000
43,ABB.N,income_statement,2019,Unusual Expense (Income),66.000000
44,ABB.N,income_statement,2018,Unusual Expense (Income),56.000000
45,ABB.N,income_statement,2017,Unusual Expense (Income),-35.000000
46,ABB.N,income_statement,2016,Unusual Expense (Income),164.000000
47,ABB.N,income_statement,2015,Unusual Expense (Income),94.000000
48,ABB.N,income_statement,2020,"Other Operating Expenses, Total",-116.000000
49,ABB.N,income_statement,2019,"Other Operating Expenses, Total",392.000000
50,ABB.N,income_statement,2020,Total Operating Expense,24703.000000
51,ABB.N,income_statement,2019,Total Operating Expense,26040.000000
52,ABB.N,income_statement,2018,Total Operating Expense,25436.000000
53,ABB.N,income_statement,2017,Total Operating Expense,22966.000000
54,ABB.N,income_statement,2016,Total Operating Expense,23000.000000
55,ABB.N,income_statement,2015,Total Operating Expense,32432.000000
56,ABB.N,income_statement,2020,Operating Income,1431.000000
57,ABB.N,income_statement,2019,Operating Income,1938.000000
58,ABB.N,income_statement,2018,Operating Income,2226.000000
59,ABB.N,income_statement,2017,Operating Income,2230.000000
60,ABB.N,income_statement,2016,Operating Income,1929.000000
61,ABB.N,income_statement,2015,Operating Income,3049.000000
62,ABB.N,income_statement,2020,"Interest Inc.(Exp.),Net-Non-Op., Total",-189.000000
63,ABB.N,income_statement,2019,"Interest Inc.(Exp.),Net-Non-Op., Total",-148.000000
64,ABB.N,income_statement,2018,"Interest Inc.(Exp.),Net-Non-Op., Total",-190.000000
65,ABB.N,income_statement,2017,"Interest Inc.(Exp.),Net-Non-Op., Total",-161.000000
66,ABB.N,income_statement,2016,"Interest Inc.(Exp.),Net-Non-Op., Total",-130.000000
67,ABB.N,income_statement,2015,"Interest Inc.(Exp.),Net-Non-Op., Total",-209.000000
68,ABB.N,income_statement,2020,"Other, Net",-401.000000
69,ABB.N,income_statement,2019,"Other, Net",72.000000
70,ABB.N,income_statement,2018,"Other, Net",83.000000
71,ABB.N,income_statement,2017,"Other, Net",33.000000
72,ABB.N,income_statement,2016,"Other, Net",-38.000000
73,ABB.N,income_statement,2020,Net Income Before Taxes,841.000000
74,ABB.N,income_statement,2019,Net Income Before Taxes,1862.000000
75,ABB.N,income_statement,2018,Net Income Before Taxes,2119.000000
76,ABB.N,income_statement,2017,Net Income Before Taxes,2102.000000
77,ABB.N,income_statement,2016,Net Income Before Taxes,1761.000000
78,ABB.N,income_statement,2015,Net Income Before Taxes,2840.000000
79,ABB.N,income_statement,2020,Provision for Income Taxes,496.000000
80,ABB.N,income_statement,2019,Provision for Income Taxes,772.000000
81,ABB.N,income_statement,2018,Provision for Income Taxes,544.000000
82,ABB.N,income_statement,2017,Provision for Income Taxes,587.000000
83,ABB.N,income_statement,2016,Provision for Income Taxes,526.000000
84,ABB.N,income_statement,2015,Provision for Income Taxes,788.000000
85,ABB.N,income_statement,2020,Net Income After Taxes,345.000000
86,ABB.N,income_statement,2019,Net Income After Taxes,1090.000000
87,ABB.N,income_statement,2018,Net Income After Taxes,1575.000000
88,ABB.N,income_statement,2017,Net Income After Taxes,1515.000000
89,ABB.N,income_statement,2016,Net Income After Taxes,1235.000000
90,ABB.N,income_statement,2015,Net Income After Taxes,2052.000000
91,ABB.N,income_statement,2020,Minority Interest,-51.000000
92,ABB.N,income_statement,2019,Minority Interest,-47.000000
93,ABB.N,income_statement,2018,Minority Interest,-125.000000
94,ABB.N,income_statement,2017,Minority Interest,-152.000000
95,ABB.N,income_statement,2016,Minority Interest,-135.000000
96,ABB.N,income_statement,2015,Minority Interest,-122.000000
97,ABB.N,income_statement,2020,Net Income Before Extra. Items,294.000000
98,ABB.N,income_statement,2019,Net Income Before Extra. Items,1043.000000
99,ABB.N,income_statement,2018,Net Income Before Extra. Items,1450.000000
100,ABB.N,income_statement,2017,Net Income Before Extra. Items,1363.000000
101,ABB.N,income_statement,2016,Net Income Before Extra. Items,1100.000000
102,ABB.N,income_statement,2015,Net Income Before Extra. Items,1930.000000
103,ABB.N,income_statement,2020,Total Extraordinary Items,4852.000000
104,ABB.N,income_statement,2019,Total Extraordinary Items,396.000000
105,ABB.N,income_statement,2018,Total Extraordinary Items,723.000000
106,ABB.N,income_statement,2017,Total Extraordinary Items,850.000000
107,ABB.N,income_statement,2016,Total Extraordinary Items,799.000000
108,ABB.N,income_statement,2015,Total Extraordinary Items,3.000000
109,ABB.N,income_statement,2020,Net Income,5146.000000
110,ABB.N,income_statement,2019,Net Income,1439.000000
111,ABB.N,income_statement,2018,Net Income,2173.000000
112,ABB.N,income_statement,2017,Net Income,2213.000000
113,ABB.N,income_statement,2016,Net Income,1899.000000
114,ABB.N,income_statement,2015,Net Income,1933.000000
115,ABB.N,income_statement,2020,Income Available to Com Excl ExtraOrd,294.000000
116,ABB.N,income_statement,2019,Income Available to Com Excl ExtraOrd,1043.000000
117,ABB.N,income_statement,2018,Income Available to Com Excl ExtraOrd,1450.000000
118,ABB.N,income_statement,2017,Income Available to Com Excl ExtraOrd,1363.000000
119,ABB.N,income_statement,2016,Income Available to Com Excl ExtraOrd,1100.000000
120,ABB.N,income_statement,2015,Income Available to Com Excl ExtraOrd,1930.000000
121,ABB.N,income_statement,2020,Income Available to Com Incl ExtraOrd,5146.000000
122,ABB.N,income_statement,2019,Income Available to Com Incl ExtraOrd,1439.000000
123,ABB.N,income_statement,2018,Income Available to Com Incl ExtraOrd,2173.000000
124,ABB.N,income_statement,2017,Income Available to Com Incl ExtraOrd,2213.000000
125,ABB.N,income_statement,2016,Income Available to Com Incl ExtraOrd,1899.000000
126,ABB.N,income_statement,2015,Income Available to Com Incl ExtraOrd,1933.000000
127,ABB.N,income_statement,2020,Dilution Adjustment,0.000000
128,ABB.N,income_statement,2019,Dilution Adjustment,0.000000
129,ABB.N,income_statement,2018,Dilution Adjustment,0.000000
130,ABB.N,income_statement,2017,Dilution Adjustment,0.000000
131,ABB.N,income_statement,2016,Dilution Adjustment,0.000000
132,ABB.N,income_statement,2015,Dilution Adjustment,0.000000
133,ABB.N,income_statement,2020,Diluted Net Income,5146.000000
134,ABB.N,income_statement,2019,Diluted Net Income,1439.000000
135,ABB.N,income_statement,2018,Diluted Net Income,2173.000000
136,ABB.N,income_statement,2017,Diluted Net Income,2213.000000
137,ABB.N,income_statement,2016,Diluted Net Income,1899.000000
138,ABB.N,income_statement,2015,Diluted Net Income,1933.000000
139,ABB.N,income_statement,2020,Diluted Weighted Average Shares,2119.000000
140,ABB.N,income_statement,2019,Diluted Weighted Average Shares,2135.000000
141,ABB.N,income_statement,2018,Diluted Weighted Average Shares,2139.000000
142,ABB.N,income_statement,2017,Diluted Weighted Average Shares,2148.000000
143,ABB.N,income_statement,2016,Diluted Weighted Average Shares,2154.000000
144,ABB.N,income_statement,2015,Diluted Weighted Average Shares,2230.000000
145,ABB.N,income_statement,2020,Diluted EPS Excluding ExtraOrd Items,0.138740
146,ABB.N,income_statement,2019,Diluted EPS Excluding ExtraOrd Items,0.488520
147,ABB.N,income_statement,2018,Diluted EPS Excluding ExtraOrd Items,0.677890
148,ABB.N,income_statement,2017,Diluted EPS Excluding ExtraOrd Items,0.634540
149,ABB.N,income_statement,2016,Diluted EPS Excluding ExtraOrd Items,0.510680
150,ABB.N,income_statement,2015,Diluted EPS Excluding ExtraOrd Items,0.865470
151,ABB.N,income_statement,2020,DPS - Common Stock Primary Issue,0.825210
152,ABB.N,income_statement,2019,DPS - Common Stock Primary Issue,0.786310
153,ABB.N,income_statement,2018,DPS - Common Stock Primary Issue,0.805990
154,ABB.N,income_statement,2017,DPS - Common Stock Primary Issue,0.762580
155,ABB.N,income_statement,2016,DPS - Common Stock Primary Issue,0.750580
156,ABB.N,income_statement,2015,DPS - Common Stock Primary Issue,0.740000
157,ABB.N,income_statement,2020,Diluted Normalized EPS,0.376870
158,ABB.N,income_statement,2019,Diluted Normalized EPS,0.633570
159,ABB.N,income_statement,2018,Diluted Normalized EPS,0.787000
160,ABB.N,income_statement,2017,Diluted Normalized EPS,0.706690
161,ABB.N,income_statement,2016,Diluted Normalized EPS,0.650030
162,ABB.N,income_statement,2015,Diluted Normalized EPS,1.153190

## EBIT KAAVA:

Revenue - Cost of Revenue, Total - Selling/General/Admin. Expenses, Total + Interest Inc.(Exp.),Net-Non-Op., Total

## key metrics

In [12]:
df_key_metrics = reuters.get_key_metrics(ticker_list)
df_key_metrics

,ticker,metric,value,financialReport
0,ABB.N,Price closing or last bid,34.95,Price and Volume
1,ABB.N,52 Week High,38.03,Price and Volume
2,ABB.N,52 Week Low,24.07,Price and Volume
3,ABB.N,Pricing date,2021-09-21,Price and Volume
4,ABB.N,10 Day Average Trading Volume,1.15,Price and Volume
5,ABB.N,Market Capitalization,"71,558.88",Price and Volume
6,ABB.N,52 Week High Date,2021-08-24,Price and Volume
7,ABB.N,52 Week Low Date,2020-10-30,Price and Volume
8,ABB.N,3 Month Average Trading Volume,25.74,Price and Volume
9,ABB.N,Beta,1.10,Price and Volume
10,ABB.N,1 Day Price Change,0.78,Price and Volume
11,ABB.N,13 Week Price Return (Daily),3.28,Price and Volume
12,ABB.N,26 Week Price Return (Daily),12.63,Price and Volume
13,ABB.N,5 Day Price Return (Daily),-5.05,Price and Volume
14,ABB.N,52 Week Price Return (Daily),38.58,Price and Volume
15,ABB.N,Year To Date Price Return (Daily),25.00,Price and Volume
16,ABB.N,Month to Date Price Return (Daily),-5.52,Price and Volume
17,ABB.N,Price Relative to S&P500 (4 Week),-5.11,Price and Volume
18,ABB.N,Price Relative to S&P500 (13 Week),0.72,Price and Volume
19,ABB.N,Price Relative to S&P500 (26 Week),1.16,Price and Volume
20,ABB.N,Price Relative to S&P500 (52 Week),4.43,Price and Volume
21,ABB.N,Price Relative to S&P500 (YTD),7.83,Price and Volume
22,ABB.N,EPS excl. Extra Items (Annual),0.14,Per Share Data
23,ABB.N,EPS excl. Extra Items (TTM),0.44,Per Share Data
24,ABB.N,EPS Normalized (Annual),0.38,Per Share Data
25,ABB.N,Revenue per Share (Annual),12.33,Per Share Data
26,ABB.N,Revenue per Share (TTM),13.65,Per Share Data
27,ABB.N,Book Value (Per Share Annual),7.72,Per Share Data
28,ABB.N,Book Value (Per Share Quarterly),6.95,Per Share Data
29,ABB.N,Tangible Book Value (Per Share Annual),1.36,Per Share Data
30,ABB.N,Tangible Book Value (Per Share Quarterly),0.63,Per Share Data
31,ABB.N,Cash Per Share (Per Share Annual),2.80,Per Share Data
32,ABB.N,Cash Per Share (Per Share Quarterly),1.99,Per Share Data
33,ABB.N,Cash Flow (Per Share Annual),0.59,Per Share Data
34,ABB.N,Cash Flow (Per Share TTM),0.91,Per Share Data
35,ABB.N,Dividend (Per Share Annual),0.83,Per Share Data
36,ABB.N,Dividends (Per Share TTM),0.83,Per Share Data
37,ABB.N,EBITD (Per Share TTM),2.17,Per Share Data
38,ABB.N,EPS Basic excl. Extra Items (Annual),0.14,Per Share Data
39,ABB.N,EPS Basic excl. Extra Items (TTM),0.45,Per Share Data
40,ABB.N,EPS incl. Extra Items (Annual),2.43,Per Share Data
41,ABB.N,EPS incl. Extra Items (TTM),2.72,Per Share Data
42,ABB.N,Free Cash Flow (Per Share TTM),0.48,Per Share Data
43,ABB.N,Dividend (Per Share 5Y),0.79,Per Share Data
44,ABB.N,P/E excl. Extra Items (Annual),251.91,Valuation
45,ABB.N,P/E excl. Extra Items (TTM),78.85,Valuation
46,ABB.N,P/E Normalized (Annual),92.74,Valuation
47,ABB.N,Price to sales (Annual),2.74,Valuation
48,ABB.N,Price to sales (TTM),2.55,Valuation
49,ABB.N,Price to Tangible Book (Annual),25.96,Valuation
50,ABB.N,Price to Tangible Book (Quarterly),56.93,Valuation
51,ABB.N,Price to Free Cash Flow (Per Share Annual),--,Valuation
52,ABB.N,Price to Cash Flow (Per Share TTM),38.04,Valuation
53,ABB.N,Price to Free Cash Flow (Per Share TTM),71.92,Valuation
54,ABB.N,Price to Book (Annual),4.53,Valuation
55,ABB.N,Price to Book (Quarterly),5.03,Valuation
56,ABB.N,P/E Basic excl. Extra Items (TTM),75.79,Valuation
57,ABB.N,P/E excl. Extra Items High (TTM),203.57,Valuation
58,ABB.N,P/E excl. Extra Items Low (TTM),23.81,Valuation
59,ABB.N,P/E incl. Extra Items (TTM),12.87,Valuation
60,ABB.N,Net Debt (Interim),"2,505.00",Valuation
61,ABB.N,Net Debt (Annual),443.00,Valuation
62,ABB.N,Dividend Yield (5Y),3.30,Valuation
63,ABB.N,Dividend Yield,2.44,Valuation
64,ABB.N,Current Dividend Yield (TTM),2.36,Valuation
65,ABB.N,Free Cash Flow (Annual),-737.00,Financial Strength
66,ABB.N,Current Ratio (Annual),1.25,Financial Strength
67,ABB.N,Net Interest coverage (Annual),13.55,Financial Strength
68,ABB.N,Long Term Debt/Equity (Annual),30.78,Financial Strength
69,ABB.N,Payout Ratio (Annual),589.97,Financial Strength
70,ABB.N,Quick Ratio (Annual),0.96,Financial Strength
71,ABB.N,Total Debt/Total Equity (Annual),39.02,Financial Strength
72,ABB.N,Current EV/Free Cash Flow (Annual),--,Financial Strength
73,ABB.N,Current EV/Free Cash Flow (TTM),--,Financial Strength
74,ABB.N,Current Ratio (Quarterly),1.12,Financial Strength
75,ABB.N,Long Term Debt/Equity (Quarterly),31.40,Financial Strength
76,ABB.N,Quick Ratio (Quarterly),0.83,Financial Strength
77,ABB.N,Total Debt/Total Equity (Quarterly),46.60,Financial Strength
78,ABB.N,Free Cash Flow (TTM),995.00,Financial Strength
79,ABB.N,Net Interest Coverage (TTM),17.66,Financial Strength
80,ABB.N,Payout Ratio (TTM),196.88,Financial Strength
81,ABB.N,Gross Margin (Annual),30.65,Margins
82,ABB.N,Gross Margin (TTM),31.66,Margins
83,ABB.N,Net Profit Margin % (Annual),1.32,Margins
84,ABB.N,Net Profit Margin (TTM),3.43,Margins
85,ABB.N,Operating Margin (Annual),5.48,Margins
86,ABB.N,Operating Margin (TTM),8.46,Margins
87,ABB.N,Pretax Margin (TTM),6.49,Margins
88,ABB.N,Pretax Margin (Annual),3.22,Margins
89,ABB.N,Operating Margin (5Y),7.40,Margins
90,ABB.N,Pretax Margin (5Y),6.58,Margins
91,ABB.N,Free Operating Cash Flow/Revenue (5Y),3.19,Margins
92,ABB.N,Free Operating Cash Flow/Revenue (TTM),3.54,Margins
93,ABB.N,Gross Margin (5Y),31.18,Margins
94,ABB.N,Net Profit Margin (5Y),4.37,Margins
95,ABB.N,Return on Assets (Annual),0.79,Management Effectiveness
96,ABB.N,Return on Equity (TTM),2.23,Management Effectiveness
97,ABB.N,Return on Average Equity (Annual),2.01,Management Effectiveness
98,ABB.N,Return on Average equity (TTM),6.75,Management Effectiveness
99,ABB.N,Return on Investment (Annual),1.36,Management Effectiveness
100,ABB.N,Return on Investment (TTM),4.15,Management Effectiveness
101,ABB.N,Return on Average Assets (5Y),2.69,Management Effectiveness
102,ABB.N,Return on Average Equity (5Y),7.42,Management Effectiveness
103,ABB.N,Return on Investment (5Y),4.57,Management Effectiveness
104,ABB.N,Asset Turnover (Annual),0.60,Management Effectiveness
105,ABB.N,Asset Turnover (TTM),0.65,Management Effectiveness
106,ABB.N,Inventory Turnover (Annual),4.19,Management Effectiveness
107,ABB.N,Inventory Turnover (TTM),4.22,Management Effectiveness
108,ABB.N,Net Income/Employee (Annual),"2,760.00",Management Effectiveness
109,ABB.N,Net Income/Employee (TTM),"9,128.79",Management Effectiveness
110,ABB.N,Receivables Turnover (Annual),3.79,Management Effectiveness
111,ABB.N,Receivables Turnover (TTM),3.63,Management Effectiveness
112,ABB.N,Revenue/Employee (Annual),"209,072.00",Management Effectiveness
113,ABB.N,Revenue/Employee (TTM),"266,231.10",Management Effectiveness
114,ABB.N,Revenue Growth (Quarterly YoY),21.04,Growth
115,ABB.N,Revenue Growth Rate (5Y),-5.93,Growth
116,ABB.N,EPS Growth (Quarterly YoY),111.56,Growth
117,ABB.N,EPS Growth (TTM YoY),-33.35,Growth
118,ABB.N,EPS Growth Rate (5Y),-30.66,Growth
119,ABB.N,Dividend Growth Rate (3Y),2.67,Growth
120,ABB.N,Revenue Growth (TTM YoY),6.78,Growth
121,ABB.N,Revenue Growth (Per Share 5Y),-4.97,Growth
122,ABB.N,Revenue Growth Rate (3Y),1.23,Growth
123,ABB.N,EPS Growth Rate (3Y),-39.76,Growth
124,ABB.N,Book Value Growth Rate (Per Share 5Y),3.17,Growth
125,ABB.N,Tangible Book Value Total Equity CAGR (5Y),2.20,Growth
126,ABB.N,Capital Spending growth rate 5 year,-4.55,Growth
127,ABB.N,EBITDA CAGR (5Y),-6.79,Growth
128,ABB.N,EBITDA Interim CAGR (5Y),-1.86,Growth
129,ABB.N,Free Operating Cash Flow CAGR (5Y),--,Growth
130,ABB.N,Total Debt CAGR (5Y),-3.83,Growth
131,ABB.N,Net Profit Margin Growth Rate (5Y),-25.58,Growth
132,ABB.N,Revenue (Annual),"26,134.00",Income Statement
133,ABB.N,Revenue (TTM),"28,114.00",Income Statement
134,ABB.N,EBITD (Annual),"3,584.00",Income Statement
135,ABB.N,EBITD (TTM),"4,466.00",Income Statement
136,ABB.N,Earnings Before Taxes (Annual),841.00,Income Statement
137,ABB.N,Earnings Before Taxes (TTM),"1,825.00",Income Statement
138,ABB.N,Net Income to Common (Annual),294.00,Income Statement
139,ABB.N,Net Income to Common (TTM),881.00,Income Statement
140,ABB.N,Earnings Before Taxes Normalized (Annual),"2,071.00",Income Statement
141,ABB.N,Net Income Available to Common Normalized (Ann...,798.58,Income Statement
142,ABB.N,Diluted Normalized EPS excl. Extra Items (TTM),0.76,Income Statement

# Reshape data

In [13]:
## Already done here, but here's how you could do it.
# df_bs = reshape_reuters_statements(df_bs)
# df_is = reshape_reuters_statements(df_is)
# ==> Doesn't have yearly data: df_key_metrics = reshape_reuters_statements(df_key_metrics)

In [14]:
df_bs

year,metric,2015,2016,2017,2018,2019,2020
0,Accounts Payable,4342.000000,4446.000000,3736.000000,4424.000000,4353.000000,4571.000000
1,"Accounts Receivable - Trade, Net",10324.000000,10037.000000,6492.000000,6833.000000,6764.000000,7045.000000
2,Accrued Expenses,NaN,2641.000000,2433.000000,2735.000000,2942.000000,3061.000000
3,"Accumulated Depreciation, Total",-6840.000000,-6926.000000,-5547.000000,-5528.000000,-5716.000000,-6364.000000
4,Additional Paid-In Capital,1175.000000,24.000000,29.000000,56.000000,73.000000,83.000000
5,Capital Lease Obligations,NaN,NaN,NaN,NaN,154.000000,160.000000
6,Cash,1837.000000,1704.000000,1963.000000,1983.000000,2111.000000,1765.000000
7,Cash & Equivalents,2717.000000,1940.000000,2563.000000,1462.000000,1433.000000,1513.000000
8,Cash and Short Term Investments,6466.000000,5853.000000,5789.000000,4297.000000,4219.000000,5678.000000
9,"Common Stock, Total",269.000000,192.000000,188.000000,188.000000,188.000000,188.000000
10,Current Port. of LT Debt/Capital Leases,1176.000000,868.000000,409.000000,1470.000000,1449.000000,1140.000000
11,Deferred Income Tax,965.000000,918.000000,1050.000000,927.000000,911.000000,661.000000
12,"Goodwill, Net",9671.000000,9501.000000,9536.000000,10764.000000,10825.000000,10850.000000
13,"Intangibles, Net",2337.000000,1996.000000,2425.000000,2607.000000,2252.000000,2078.000000
14,Long Term Debt,5985.000000,5800.000000,6682.000000,6587.000000,6618.000000,4668.000000
15,Long Term Investments,263.000000,282.000000,279.000000,112.000000,51.000000,1808.000000
16,Minority Interest,507.000000,502.000000,530.000000,582.000000,454.000000,314.000000
17,Note Receivable - Long Term,NaN,112.000000,108.000000,30.000000,30.000000,NaN
18,Notes Payable/Short Term Debt,278.000000,135.000000,317.000000,561.000000,838.000000,153.000000
19,"Other Current Assets, Total",1251.000000,980.000000,5448.000000,5640.000000,10405.000000,1073.000000
20,"Other Current liabilities, Total",10048.000000,7059.000000,9574.000000,9257.000000,10684.000000,6491.000000
21,"Other Equity, Total",-4865.000000,-5194.000000,-4353.000000,-5307.000000,-5600.000000,-4019.000000
22,"Other Liabilities, Total",3574.000000,3438.000000,3908.000000,3946.000000,4179.000000,4184.000000
23,"Other Long Term Assets, Total",1049.000000,1516.000000,5171.000000,4930.000000,1526.000000,1983.000000
24,Prepaid Expenses,225.000000,176.000000,159.000000,176.000000,191.000000,201.000000
25,"Property/Plant/Equipment, Total - Gross",12116.000000,11669.000000,9351.000000,9661.000000,10682.000000,11507.000000
26,"Property/Plant/Equipment, Total - Net",5276.000000,4743.000000,3804.000000,4133.000000,4966.000000,5143.000000
27,Retained Earnings (Accumulated Deficit),20476.000000,19925.000000,19594.000000,19839.000000,19640.000000,22946.000000
28,Short Term Investments,1912.000000,2209.000000,1263.000000,852.000000,675.000000,2400.000000
29,"Tangible Book Value per Share, Common Eq",1.128390,0.887450,1.336380,0.272520,0.210450,1.357570
30,Total Assets,41356.000000,39202.000000,43458.000000,44441.000000,46108.000000,41088.000000
31,Total Common Shares Outstanding,2191.625140,2138.706840,2138.606490,2131.962410,2133.501110,2030.834170
32,Total Current Assets,22760.000000,21052.000000,22135.000000,21865.000000,26458.000000,19226.000000
33,Total Current Liabilities,15844.000000,15149.000000,16469.000000,18447.000000,20266.000000,15416.000000
34,Total Debt,7439.000000,6803.000000,7408.000000,8618.000000,9059.000000,6121.000000
35,Total Equity,14481.000000,13395.000000,14819.000000,13952.000000,13526.000000,15685.000000
36,Total Inventory,4757.000000,4347.000000,3737.000000,4284.000000,4184.000000,4469.000000
37,Total Liabilities,26875.000000,25807.000000,28639.000000,30489.000000,32582.000000,25403.000000
38,Total Liabilities & Shareholders' Equity,41356.000000,39202.000000,43458.000000,44441.000000,46108.000000,41088.000000
39,Total Long Term Debt,5985.000000,5800.000000,6682.000000,6587.000000,6772.000000,4828.000000
40,"Total Receivables, Net",10061.000000,9696.000000,7002.000000,7468.000000,7459.000000,7805.000000
41,Treasury Stock - Common,-2581.000000,-1559.000000,-647.000000,-820.000000,-785.000000,-3530.000000
42,Unrealized Gain (Loss),7.000000,7.000000,8.000000,-4.000000,10.000000,17.000000

In [15]:
# df_bs['2020'][df_bs['metric'] == 'Total Current Assets']#[df_bs['metric'] == 'Total Current Assets'].values[0]

### Get total current assets

In [16]:
total_current_assets = int(float(df_bs[2020][df_bs['metric'] == 'Total Current Assets'].iloc[0]))
total_current_liabilities = get_metric_latest_bs(df_bs, 'Total Current Liabilities')
print(int(total_current_assets))
print(type(total_current_liabilities))
# Working capital = total_current_assets - total_current_liabilities
working_capital = total_current_assets - total_current_liabilities
print(working_capital)

total_assets = get_metric_latest_bs(df_bs, 'Total Assets')
print(total_assets)

A = working_capital/(float(total_assets))
print(A)

19226
<class 'int'>
3810
41088
0.09272780373831775

In [17]:
# B
retained_earnings = get_metric_latest_bs(df_bs, 'Retained Earnings (Accumulated Deficit)')
retained_earnings
B = retained_earnings/(float(total_assets))
B

0.5584598909657321

In [18]:
# C = Earnings before interest / total assets
ebit = get_metric_latest_bs(df_is, 'Revenue') - get_metric_latest_bs(df_is, 'Total Operating Expense')
C = ebit / float(total_assets)
print(C)

0.03482768691588785

## D = Market Value of Equity / Total Liabilities

In [19]:
import yfinance as yf
pd.set_option('display.float_format', str)
ticker = yf.Ticker("AMZN")

In [20]:
from yahoofinancials import YahooFinancials

ticker = 'ABB'
yahoo_financials = YahooFinancials(ticker)

# Hakee hinnan
yahoo_financials.get_prev_close_price()

# prev close 22.9.2021
price = yahoo_financials.get_prev_close_price()

ticker_yfinance = yf.Ticker(ticker)
shares = ticker_yfinance.info['sharesOutstanding']

# Kaikki muut arvot ilmoitettu miljoonissa
market_value_of_equity = (price*shares)/(1000000)

liabilities = get_metric_latest_bs(df_bs,'Total Liabilities')
print(liabilities)

D = market_value_of_equity/float(liabilities)
print("D: ", D)

E = get_metric_latest_bs(df_is, 'Revenue') / float(get_metric_latest_bs(df_bs, 'Total Assets'))
print("E: ", E)

25403
D:  2.7598984371924575
E:  0.6360494548286605

In [21]:
Z = (1.2*A)+(1.4*B)+(3.3*C)+(0.6*D)+(1.0*E)
print("Z: ", Z)

Z:  3.3000370958045706

# Z-Score:

* AMZN: 6.150276669527528

In [146]:
df_key_metrics

,ticker,metric,value,financialReport
0,AMZN.O,Price closing or last bid,"3,462.52",Price and Volume
1,AMZN.O,52 Week High,"3,773.08",Price and Volume
2,AMZN.O,52 Week Low,"2,871.00",Price and Volume
3,AMZN.O,Pricing date,2021-09-17,Price and Volume
4,AMZN.O,10 Day Average Trading Volume,2.79,Price and Volume
5,AMZN.O,Market Capitalization,"1,753,560.00",Price and Volume
6,AMZN.O,52 Week High Date,2021-07-13,Price and Volume
7,AMZN.O,52 Week Low Date,2020-09-21,Price and Volume
8,AMZN.O,3 Month Average Trading Volume,68.35,Price and Volume
9,AMZN.O,Beta,1.15,Price and Volume
10,AMZN.O,1 Day Price Change,-0.74,Price and Volume
11,AMZN.O,13 Week Price Return (Daily),-0.70,Price and Volume
12,AMZN.O,26 Week Price Return (Daily),12.60,Price and Volume
13,AMZN.O,5 Day Price Return (Daily),-0.19,Price and Volume
14,AMZN.O,52 Week Price Return (Daily),15.08,Price and Volume
15,AMZN.O,Year To Date Price Return (Daily),6.31,Price and Volume
16,AMZN.O,Month to Date Price Return (Daily),-0.24,Price and Volume
17,AMZN.O,Price Relative to S&P500 (4 Week),8.42,Price and Volume
18,AMZN.O,Price Relative to S&P500 (13 Week),-6.67,Price and Volume
19,AMZN.O,Price Relative to S&P500 (26 Week),-0.60,Price and Volume
20,AMZN.O,Price Relative to S&P500 (52 Week),-12.85,Price and Volume
21,AMZN.O,Price Relative to S&P500 (YTD),-9.92,Price and Volume
22,AMZN.O,EPS excl. Extra Items (Annual),41.83,Per Share Data
23,AMZN.O,EPS excl. Extra Items (TTM),57.38,Per Share Data
24,AMZN.O,EPS Normalized (Annual),61.70,Per Share Data
25,AMZN.O,Revenue per Share (Annual),756.99,Per Share Data
26,AMZN.O,Revenue per Share (TTM),864.13,Per Share Data
27,AMZN.O,Book Value (Per Share Annual),185.69,Per Share Data
28,AMZN.O,Book Value (Per Share Quarterly),226.88,Per Share Data
29,AMZN.O,Tangible Book Value (Per Share Annual),145.94,Per Share Data
30,AMZN.O,Tangible Book Value (Per Share Quarterly),196.55,Per Share Data
31,AMZN.O,Cash Per Share (Per Share Annual),167.79,Per Share Data
32,AMZN.O,Cash Per Share (Per Share Quarterly),177.66,Per Share Data
33,AMZN.O,Cash Flow (Per Share Annual),74.56,Per Share Data
34,AMZN.O,Cash Flow (Per Share TTM),115.02,Per Share Data
35,AMZN.O,Dividend (Per Share Annual),--,Per Share Data
36,AMZN.O,Dividends (Per Share TTM),0.00,Per Share Data
37,AMZN.O,EBITD (Per Share TTM),137.08,Per Share Data
38,AMZN.O,EPS Basic excl. Extra Items (Annual),42.66,Per Share Data
39,AMZN.O,EPS Basic excl. Extra Items (TTM),58.57,Per Share Data
40,AMZN.O,EPS incl. Extra Items (Annual),41.83,Per Share Data
41,AMZN.O,EPS incl. Extra Items (TTM),57.38,Per Share Data
42,AMZN.O,Free Cash Flow (Per Share TTM),13.78,Per Share Data
43,AMZN.O,Dividend (Per Share 5Y),--,Per Share Data
44,AMZN.O,P/E excl. Extra Items (Annual),82.78,Valuation
45,AMZN.O,P/E excl. Extra Items (TTM),60.35,Valuation
46,AMZN.O,P/E Normalized (Annual),56.11,Valuation
47,AMZN.O,Price to sales (Annual),4.54,Valuation
48,AMZN.O,Price to sales (TTM),3.96,Valuation
49,AMZN.O,Price to Tangible Book (Annual),23.89,Valuation
50,AMZN.O,Price to Tangible Book (Quarterly),17.63,Valuation
51,AMZN.O,Price to Free Cash Flow (Per Share Annual),67.64,Valuation
52,AMZN.O,Price to Cash Flow (Per Share TTM),29.72,Valuation
53,AMZN.O,Price to Free Cash Flow (Per Share TTM),248.13,Valuation
54,AMZN.O,Price to Book (Annual),18.65,Valuation
55,AMZN.O,Price to Book (Quarterly),15.26,Valuation
56,AMZN.O,P/E Basic excl. Extra Items (TTM),58.74,Valuation
57,AMZN.O,P/E excl. Extra Items High (TTM),257.06,Valuation
58,AMZN.O,P/E excl. Extra Items Low (TTM),58.88,Valuation
59,AMZN.O,P/E incl. Extra Items (TTM),60.35,Valuation
60,AMZN.O,Net Debt (Interim),"-22,229.00",Valuation
61,AMZN.O,Net Debt (Annual),"-33,365.00",Valuation
62,AMZN.O,Dividend Yield (5Y),--,Valuation
63,AMZN.O,Dividend Yield,--,Valuation
64,AMZN.O,Current Dividend Yield (TTM),0.00,Valuation
65,AMZN.O,Free Cash Flow (Annual),"25,924.00",Financial Strength
66,AMZN.O,Current Ratio (Annual),1.05,Financial Strength
67,AMZN.O,Net Interest coverage (Annual),153.57,Financial Strength
68,AMZN.O,Long Term Debt/Equity (Annual),53.40,Financial Strength
69,AMZN.O,Payout Ratio (Annual),--,Financial Strength
70,AMZN.O,Quick Ratio (Annual),0.86,Financial Strength
71,AMZN.O,Total Debt/Total Equity (Annual),54.63,Financial Strength
72,AMZN.O,Current EV/Free Cash Flow (Annual),--,Financial Strength
73,AMZN.O,Current EV/Free Cash Flow (TTM),256.53,Financial Strength
74,AMZN.O,Current Ratio (Quarterly),1.20,Financial Strength
75,AMZN.O,Long Term Debt/Equity (Quarterly),57.93,Financial Strength
76,AMZN.O,Quick Ratio (Quarterly),0.99,Financial Strength
77,AMZN.O,Total Debt/Total Equity (Quarterly),58.94,Financial Strength
78,AMZN.O,Free Cash Flow (TTM),"7,067.00",Financial Strength
79,AMZN.O,Net Interest Coverage (TTM),89.31,Financial Strength
80,AMZN.O,Payout Ratio (TTM),0.00,Financial Strength
81,AMZN.O,Gross Margin (Annual),39.57,Margins
82,AMZN.O,Gross Margin (TTM),40.68,Margins
83,AMZN.O,Net Profit Margin % (Annual),5.52,Margins
84,AMZN.O,Net Profit Margin (TTM),6.61,Margins
85,AMZN.O,Operating Margin (Annual),5.93,Margins
86,AMZN.O,Operating Margin (TTM),6.68,Margins
87,AMZN.O,Pretax Margin (TTM),7.55,Margins
88,AMZN.O,Pretax Margin (Annual),6.26,Margins
89,AMZN.O,Operating Margin (5Y),4.79,Margins
90,AMZN.O,Pretax Margin (5Y),4.71,Margins
91,AMZN.O,Free Operating Cash Flow/Revenue (5Y),6.65,Margins
92,AMZN.O,Free Operating Cash Flow/Revenue (TTM),1.59,Margins
93,AMZN.O,Gross Margin (5Y),39.16,Margins
94,AMZN.O,Net Profit Margin (5Y),3.92,Margins
95,AMZN.O,Return on Assets (Annual),7.80,Management Effectiveness
96,AMZN.O,Return on Equity (TTM),9.48,Management Effectiveness
97,AMZN.O,Return on Average Equity (Annual),27.44,Management Effectiveness
98,AMZN.O,Return on Average equity (TTM),31.23,Management Effectiveness
99,AMZN.O,Return on Investment (Annual),12.83,Management Effectiveness
100,AMZN.O,Return on Investment (TTM),14.41,Management Effectiveness
101,AMZN.O,Return on Average Assets (5Y),5.98,Management Effectiveness
102,AMZN.O,Return on Average Equity (5Y),23.03,Management Effectiveness
103,AMZN.O,Return on Investment (5Y),10.39,Management Effectiveness
104,AMZN.O,Asset Turnover (Annual),1.41,Management Effectiveness
105,AMZN.O,Asset Turnover (TTM),1.43,Management Effectiveness
106,AMZN.O,Inventory Turnover (Annual),10.53,Management Effectiveness
107,AMZN.O,Inventory Turnover (TTM),12.03,Management Effectiveness
108,AMZN.O,Net Income/Employee (Annual),"20,338.74",Management Effectiveness
109,AMZN.O,Net Income/Employee (TTM),"22,587.06",Management Effectiveness
110,AMZN.O,Receivables Turnover (Annual),17.22,Management Effectiveness
111,AMZN.O,Receivables Turnover (TTM),19.11,Management Effectiveness
112,AMZN.O,Revenue/Employee (Annual),"368,381.70",Management Effectiveness
113,AMZN.O,Revenue/Employee (TTM),"341,523.90",Management Effectiveness
114,AMZN.O,Revenue Growth (Quarterly YoY),27.18,Growth
115,AMZN.O,Revenue Growth Rate (5Y),29.26,Growth
116,AMZN.O,EPS Growth (Quarterly YoY),46.91,Growth
117,AMZN.O,EPS Growth (TTM YoY),120.55,Growth
118,AMZN.O,EPS Growth Rate (5Y),101.81,Growth
119,AMZN.O,Dividend Growth Rate (3Y),--,Growth
120,AMZN.O,Revenue Growth (TTM YoY),37.76,Growth
121,AMZN.O,Revenue Growth (Per Share 5Y),27.54,Growth
122,AMZN.O,Revenue Growth Rate (3Y),29.48,Growth
123,AMZN.O,EPS Growth Rate (3Y),109.45,Growth
124,AMZN.O,Book Value Growth Rate (Per Share 5Y),45.56,Growth
125,AMZN.O,Tangible Book Value Total Equity CAGR (5Y),53.43,Growth
126,AMZN.O,Capital Spending growth rate 5 year,49.43,Growth
127,AMZN.O,EBITDA CAGR (5Y),47.34,Growth
128,AMZN.O,EBITDA Interim CAGR (5Y),45.03,Growth
129,AMZN.O,Free Operating Cash Flow CAGR (5Y),31.27,Growth
130,AMZN.O,Total Debt CAGR (5Y),24.19,Growth
131,AMZN.O,Net Profit Margin Growth Rate (5Y),57.07,Growth
132,AMZN.O,Revenue (Annual),"386,064.00",Income Statement
133,AMZN.O,Revenue (TTM),"443,298.00",Income Statement
134,AMZN.O,EBITD (Annual),"51,108.00",Income Statement
135,AMZN.O,EBITD (TTM),"70,321.00",Income Statement
136,AMZN.O,Earnings Before Taxes (Annual),"24,178.00",Income Statement
137,AMZN.O,Earnings Before Taxes (TTM),"33,476.00",Income Statement
138,AMZN.O,Net Income to Common (Annual),"21,331.00",Income Statement
139,AMZN.O,Net Income to Common (TTM),"29,438.00",Income Statement
140,AMZN.O,Earnings Before Taxes Normalized (Annual),"35,678.00",Income Statement
141,AMZN.O,Net Income Available to Common Normalized (Ann...,"31,469.25",Income Statement
142,AMZN.O,Diluted Normalized EPS excl. Extra Items (TTM),76.58,Income Statement

In [117]:
df_is

year,metric,2015,2016,2017,2018,2019,2020
0,"Cost of Revenue, Total",71651.000000,88265.000000,111934.000000,139156.000000,165536.000000,233307.000000
1,DPS - Common Stock Primary Issue,NaN,0.000000,NaN,NaN,NaN,NaN
2,Depreciation/Amortization,228.000000,287.000000,366.000000,475.000000,565.000000,509.000000
3,Diluted EPS Excluding ExtraOrd Items,1.249480,4.898760,4.551720,19.832000,22.992060,41.825490
4,Diluted Net Income,596.000000,2371.000000,3033.000000,10073.000000,11588.000000,21331.000000
5,Diluted Normalized EPS,1.249480,4.898760,4.551720,19.832000,22.992060,61.704400
6,Diluted Weighted Average Shares,477.000000,484.000000,493.000000,500.000000,504.000000,510.000000
7,Dilution Adjustment,0.000000,NaN,NaN,NaN,NaN,NaN
8,Equity In Affiliates,-22.000000,-96.000000,-4.000000,9.000000,-14.000000,16.000000
9,Gross Profit,35355.000000,47722.000000,65932.000000,93731.000000,114986.000000,152757.000000
10,Income Available to Com Excl ExtraOrd,596.000000,2371.000000,2244.000000,9916.000000,11588.000000,21331.000000
11,Income Available to Com Incl ExtraOrd,596.000000,2371.000000,3033.000000,10073.000000,11588.000000,21331.000000
12,"Interest Inc.(Exp.),Net-Non-Op., Total",-680.000000,-371.000000,-406.000000,-977.000000,-557.000000,-224.000000
13,Net Income,596.000000,2371.000000,3033.000000,10073.000000,11588.000000,21331.000000
14,Net Income After Taxes,618.000000,2467.000000,2248.000000,9907.000000,11602.000000,21315.000000
15,Net Income Before Extra. Items,596.000000,2371.000000,2244.000000,9916.000000,11588.000000,21331.000000
16,Net Income Before Taxes,1568.000000,3892.000000,3806.000000,11261.000000,13976.000000,24178.000000
17,Operating Income,2233.000000,4186.000000,4106.000000,12421.000000,14541.000000,22899.000000
18,"Other Operating Expenses, Total",-57.000000,-120.000000,-152.000000,-179.000000,-364.000000,-584.000000
19,"Other, Net",15.000000,77.000000,106.000000,-183.000000,-8.000000,1503.000000
20,Provision for Income Taxes,950.000000,1425.000000,1558.000000,1354.000000,2374.000000,2863.000000
21,Research & Development,12540.000000,16085.000000,22620.000000,28837.000000,35931.000000,42740.000000
22,Revenue,107006.000000,135987.000000,177866.000000,232887.000000,280522.000000,386064.000000
23,"Selling/General/Admin. Expenses, Total",20411.000000,27284.000000,38992.000000,52177.000000,64313.000000,87193.000000
24,Total Extraordinary Items,NaN,NaN,789.000000,157.000000,0.000000,0.000000
25,Total Operating Expense,104773.000000,131801.000000,173760.000000,220466.000000,265981.000000,363165.000000
26,Total Revenue,107006.000000,135987.000000,177866.000000,232887.000000,280522.000000,386064.000000

In [115]:
df_key_metrics

,ticker,metric,value,financialReport
0,AMZN.O,Price closing or last bid,"3,462.52",Price and Volume
1,AMZN.O,52 Week High,"3,773.08",Price and Volume
2,AMZN.O,52 Week Low,"2,871.00",Price and Volume
3,AMZN.O,Pricing date,2021-09-20,Price and Volume
4,AMZN.O,10 Day Average Trading Volume,2.79,Price and Volume
5,AMZN.O,Market Capitalization,"1,753,560.00",Price and Volume
6,AMZN.O,52 Week High Date,2021-07-13,Price and Volume
7,AMZN.O,52 Week Low Date,2020-09-21,Price and Volume
8,AMZN.O,3 Month Average Trading Volume,68.35,Price and Volume
9,AMZN.O,Beta,1.15,Price and Volume
10,AMZN.O,1 Day Price Change,-0.74,Price and Volume
11,AMZN.O,13 Week Price Return (Daily),-0.70,Price and Volume
12,AMZN.O,26 Week Price Return (Daily),12.60,Price and Volume
13,AMZN.O,5 Day Price Return (Daily),-0.19,Price and Volume
14,AMZN.O,52 Week Price Return (Daily),15.08,Price and Volume
15,AMZN.O,Year To Date Price Return (Daily),6.31,Price and Volume
16,AMZN.O,Month to Date Price Return (Daily),-0.24,Price and Volume
17,AMZN.O,Price Relative to S&P500 (4 Week),8.42,Price and Volume
18,AMZN.O,Price Relative to S&P500 (13 Week),-6.67,Price and Volume
19,AMZN.O,Price Relative to S&P500 (26 Week),-0.60,Price and Volume
20,AMZN.O,Price Relative to S&P500 (52 Week),-12.85,Price and Volume
21,AMZN.O,Price Relative to S&P500 (YTD),-9.92,Price and Volume
22,AMZN.O,EPS excl. Extra Items (Annual),41.83,Per Share Data
23,AMZN.O,EPS excl. Extra Items (TTM),57.38,Per Share Data
24,AMZN.O,EPS Normalized (Annual),61.70,Per Share Data
25,AMZN.O,Revenue per Share (Annual),756.99,Per Share Data
26,AMZN.O,Revenue per Share (TTM),864.13,Per Share Data
27,AMZN.O,Book Value (Per Share Annual),185.69,Per Share Data
28,AMZN.O,Book Value (Per Share Quarterly),226.88,Per Share Data
29,AMZN.O,Tangible Book Value (Per Share Annual),145.94,Per Share Data
30,AMZN.O,Tangible Book Value (Per Share Quarterly),196.55,Per Share Data
31,AMZN.O,Cash Per Share (Per Share Annual),167.79,Per Share Data
32,AMZN.O,Cash Per Share (Per Share Quarterly),177.66,Per Share Data
33,AMZN.O,Cash Flow (Per Share Annual),74.56,Per Share Data
34,AMZN.O,Cash Flow (Per Share TTM),115.02,Per Share Data
35,AMZN.O,Dividend (Per Share Annual),--,Per Share Data
36,AMZN.O,Dividends (Per Share TTM),0.00,Per Share Data
37,AMZN.O,EBITD (Per Share TTM),137.08,Per Share Data
38,AMZN.O,EPS Basic excl. Extra Items (Annual),42.66,Per Share Data
39,AMZN.O,EPS Basic excl. Extra Items (TTM),58.57,Per Share Data
40,AMZN.O,EPS incl. Extra Items (Annual),41.83,Per Share Data
41,AMZN.O,EPS incl. Extra Items (TTM),57.38,Per Share Data
42,AMZN.O,Free Cash Flow (Per Share TTM),13.78,Per Share Data
43,AMZN.O,Dividend (Per Share 5Y),--,Per Share Data
44,AMZN.O,P/E excl. Extra Items (Annual),82.78,Valuation
45,AMZN.O,P/E excl. Extra Items (TTM),60.35,Valuation
46,AMZN.O,P/E Normalized (Annual),56.11,Valuation
47,AMZN.O,Price to sales (Annual),4.54,Valuation
48,AMZN.O,Price to sales (TTM),3.96,Valuation
49,AMZN.O,Price to Tangible Book (Annual),23.89,Valuation
50,AMZN.O,Price to Tangible Book (Quarterly),17.63,Valuation
51,AMZN.O,Price to Free Cash Flow (Per Share Annual),67.64,Valuation
52,AMZN.O,Price to Cash Flow (Per Share TTM),29.72,Valuation
53,AMZN.O,Price to Free Cash Flow (Per Share TTM),248.13,Valuation
54,AMZN.O,Price to Book (Annual),18.65,Valuation
55,AMZN.O,Price to Book (Quarterly),15.26,Valuation
56,AMZN.O,P/E Basic excl. Extra Items (TTM),58.74,Valuation
57,AMZN.O,P/E excl. Extra Items High (TTM),257.06,Valuation
58,AMZN.O,P/E excl. Extra Items Low (TTM),58.88,Valuation
59,AMZN.O,P/E incl. Extra Items (TTM),60.35,Valuation
60,AMZN.O,Net Debt (Interim),"-22,229.00",Valuation
61,AMZN.O,Net Debt (Annual),"-33,365.00",Valuation
62,AMZN.O,Dividend Yield (5Y),--,Valuation
63,AMZN.O,Dividend Yield,--,Valuation
64,AMZN.O,Current Dividend Yield (TTM),0.00,Valuation
65,AMZN.O,Free Cash Flow (Annual),"25,924.00",Financial Strength
66,AMZN.O,Current Ratio (Annual),1.05,Financial Strength
67,AMZN.O,Net Interest coverage (Annual),153.57,Financial Strength
68,AMZN.O,Long Term Debt/Equity (Annual),53.40,Financial Strength
69,AMZN.O,Payout Ratio (Annual),--,Financial Strength
70,AMZN.O,Quick Ratio (Annual),0.86,Financial Strength
71,AMZN.O,Total Debt/Total Equity (Annual),54.63,Financial Strength
72,AMZN.O,Current EV/Free Cash Flow (Annual),--,Financial Strength
73,AMZN.O,Current EV/Free Cash Flow (TTM),256.53,Financial Strength
74,AMZN.O,Current Ratio (Quarterly),1.20,Financial Strength
75,AMZN.O,Long Term Debt/Equity (Quarterly),57.93,Financial Strength
76,AMZN.O,Quick Ratio (Quarterly),0.99,Financial Strength
77,AMZN.O,Total Debt/Total Equity (Quarterly),58.94,Financial Strength
78,AMZN.O,Free Cash Flow (TTM),"7,067.00",Financial Strength
79,AMZN.O,Net Interest Coverage (TTM),89.31,Financial Strength
80,AMZN.O,Payout Ratio (TTM),0.00,Financial Strength
81,AMZN.O,Gross Margin (Annual),39.57,Margins
82,AMZN.O,Gross Margin (TTM),40.68,Margins
83,AMZN.O,Net Profit Margin % (Annual),5.52,Margins
84,AMZN.O,Net Profit Margin (TTM),6.61,Margins
85,AMZN.O,Operating Margin (Annual),5.93,Margins
86,AMZN.O,Operating Margin (TTM),6.68,Margins
87,AMZN.O,Pretax Margin (TTM),7.55,Margins
88,AMZN.O,Pretax Margin (Annual),6.26,Margins
89,AMZN.O,Operating Margin (5Y),4.79,Margins
90,AMZN.O,Pretax Margin (5Y),4.71,Margins
91,AMZN.O,Free Operating Cash Flow/Revenue (5Y),6.65,Margins
92,AMZN.O,Free Operating Cash Flow/Revenue (TTM),1.59,Margins
93,AMZN.O,Gross Margin (5Y),39.16,Margins
94,AMZN.O,Net Profit Margin (5Y),3.92,Margins
95,AMZN.O,Return on Assets (Annual),7.80,Management Effectiveness
96,AMZN.O,Return on Equity (TTM),9.48,Management Effectiveness
97,AMZN.O,Return on Average Equity (Annual),27.44,Management Effectiveness
98,AMZN.O,Return on Average equity (TTM),31.23,Management Effectiveness
99,AMZN.O,Return on Investment (Annual),12.83,Management Effectiveness
100,AMZN.O,Return on Investment (TTM),14.41,Management Effectiveness
101,AMZN.O,Return on Average Assets (5Y),5.98,Management Effectiveness
102,AMZN.O,Return on Average Equity (5Y),23.03,Management Effectiveness
103,AMZN.O,Return on Investment (5Y),10.39,Management Effectiveness
104,AMZN.O,Asset Turnover (Annual),1.41,Management Effectiveness
105,AMZN.O,Asset Turnover (TTM),1.43,Management Effectiveness
106,AMZN.O,Inventory Turnover (Annual),10.53,Management Effectiveness
107,AMZN.O,Inventory Turnover (TTM),12.03,Management Effectiveness
108,AMZN.O,Net Income/Employee (Annual),"20,338.74",Management Effectiveness
109,AMZN.O,Net Income/Employee (TTM),"22,587.06",Management Effectiveness
110,AMZN.O,Receivables Turnover (Annual),17.22,Management Effectiveness
111,AMZN.O,Receivables Turnover (TTM),19.11,Management Effectiveness
112,AMZN.O,Revenue/Employee (Annual),"368,381.70",Management Effectiveness
113,AMZN.O,Revenue/Employee (TTM),"341,523.90",Management Effectiveness
114,AMZN.O,Revenue Growth (Quarterly YoY),27.18,Growth
115,AMZN.O,Revenue Growth Rate (5Y),29.26,Growth
116,AMZN.O,EPS Growth (Quarterly YoY),46.91,Growth
117,AMZN.O,EPS Growth (TTM YoY),120.55,Growth
118,AMZN.O,EPS Growth Rate (5Y),101.81,Growth
119,AMZN.O,Dividend Growth Rate (3Y),--,Growth
120,AMZN.O,Revenue Growth (TTM YoY),37.76,Growth
121,AMZN.O,Revenue Growth (Per Share 5Y),27.54,Growth
122,AMZN.O,Revenue Growth Rate (3Y),29.48,Growth
123,AMZN.O,EPS Growth Rate (3Y),109.45,Growth
124,AMZN.O,Book Value Growth Rate (Per Share 5Y),45.56,Growth
125,AMZN.O,Tangible Book Value Total Equity CAGR (5Y),53.43,Growth
126,AMZN.O,Capital Spending growth rate 5 year,49.43,Growth
127,AMZN.O,EBITDA CAGR (5Y),47.34,Growth
128,AMZN.O,EBITDA Interim CAGR (5Y),45.03,Growth
129,AMZN.O,Free Operating Cash Flow CAGR (5Y),31.27,Growth
130,AMZN.O,Total Debt CAGR (5Y),24.19,Growth
131,AMZN.O,Net Profit Margin Growth Rate (5Y),57.07,Growth
132,AMZN.O,Revenue (Annual),"386,064.00",Income Statement
133,AMZN.O,Revenue (TTM),"443,298.00",Income Statement
134,AMZN.O,EBITD (Annual),"51,108.00",Income Statement
135,AMZN.O,EBITD (TTM),"70,321.00",Income Statement
136,AMZN.O,Earnings Before Taxes (Annual),"24,178.00",Income Statement
137,AMZN.O,Earnings Before Taxes (TTM),"33,476.00",Income Statement
138,AMZN.O,Net Income to Common (Annual),"21,331.00",Income Statement
139,AMZN.O,Net Income to Common (TTM),"29,438.00",Income Statement
140,AMZN.O,Earnings Before Taxes Normalized (Annual),"35,678.00",Income Statement
141,AMZN.O,Net Income Available to Common Normalized (Ann...,"31,469.25",Income Statement
142,AMZN.O,Diluted Normalized EPS excl. Extra Items (TTM),76.58,Income Statement

In [78]:
value = get_metric_latest_bs(df_bs, 'Total Current Assets')
print(value)

29    132733.000000
Name: 2020, dtype: object

In [116]:
df_cf

year,metric,2015,2016,2017,2018,2019,2020
0,Capital Expenditures,-5387.000000,-7804.000000,-11955.000000,-13427.000000,-16861.000000,-40140.000000
1,Cash Interest Paid,325.000000,290.000000,328.000000,854.000000,875.000000,916.000000
2,Cash Taxes Paid,273.000000,412.000000,957.000000,1184.000000,-881.000000,1713.000000
3,Cash from Financing Activities,-3882.000000,-3716.000000,9928.000000,-7686.000000,-10066.000000,-1104.000000
4,Cash from Investing Activities,-6450.000000,-9516.000000,-27084.000000,-12369.000000,-24281.000000,-59611.000000
5,Cash from Operating Activities,12039.000000,17203.000000,18365.000000,30723.000000,38514.000000,66064.000000
6,Changes in Working Capital,2557.000000,3847.000000,-242.000000,-1043.000000,-2438.000000,13481.000000
7,Deferred Taxes,81.000000,-246.000000,-29.000000,441.000000,796.000000,-554.000000
8,Depreciation/Depletion,6281.000000,8116.000000,11478.000000,15341.000000,21789.000000,25251.000000
9,Foreign Exchange Effects,-374.000000,-212.000000,713.000000,-351.000000,70.000000,618.000000
10,"Issuance (Retirement) of Debt, Net",-3882.000000,-3716.000000,9928.000000,-7686.000000,-10066.000000,-1104.000000
11,Net Change in Cash,1333.000000,3759.000000,1922.000000,10317.000000,4237.000000,5967.000000
12,Net Income/Starting Line,596.000000,2371.000000,3033.000000,10073.000000,11588.000000,21331.000000
13,Non-Cash Items,2524.000000,3115.000000,4125.000000,5911.000000,6779.000000,6555.000000
14,"Other Investing Cash Flow Items, Total",-1063.000000,-1712.000000,-15129.000000,1058.000000,-7420.000000,-19471.000000

In [136]:
import yfinance as yf
pd.set_option('display.float_format', str)
msft = yf.Ticker("AMZN")
msft.financials

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Research Development,42740000000.0,35931000000.0,28837000000.0,22620000000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,24194000000.0,13962000000.0,11270000000.0,3802000000.0
Minority Interest,None,None,None,None
Net Income,21331000000.0,11588000000.0,10073000000.0,3033000000.0
Selling General Administrative,87193000000.0,64313000000.0,52177000000.0,38992000000.0
Gross Profit,152757000000.0,114986000000.0,93731000000.0,65932000000.0
Ebit,22899000000.0,14404000000.0,12421000000.0,4106000000.0
Operating Income,22899000000.0,14404000000.0,12421000000.0,4106000000.0
Other Operating Expenses,-75000000.0,338000000.0,296000000.0,214000000.0
Interest Expense,-1647000000.0,-1600000000.0,-1417000000.0,-848000000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,2863000000.0,2374000000.0,1197000000.0,769000000.0
Total Revenue,386064000000.0,280522000000.0,232887000000.0,177866000000.0
Total Operating Expenses,363165000000.0,266118000000.0,220466000000.0,173760000000.0
Cost Of Revenue,233307000000.0,165536000000.0,139156000000.0,111934000000.0
Total Other Income Expense Net,1295000000.0,-442000000.0,-1151000000.0,-304000000.0
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,21331000000.0,11588000000.0,10073000000.0,3033000000.0
Net Income Applicable To Common Shares,21331000000.0,11588000000.0,10073000000.0,3033000000.0

In [137]:
msft.cashflow

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Investments,-22242000000.0,-9131000000.0,1140000000.0,-3054000000.0
Change To Liabilities,18745000000.0,9904000000.0,4414000000.0,7838000000.0
Total Cashflows From Investing Activities,-59611000000.0,-24281000000.0,-12369000000.0,-27084000000.0
Net Borrowings,-1104000000.0,-10066000000.0,-7686000000.0,9928000000.0
Total Cash From Financing Activities,-1104000000.0,-10066000000.0,-7686000000.0,9928000000.0
Change To Operating Activities,5754000000.0,-1383000000.0,472000000.0,283000000.0
Net Income,21331000000.0,11588000000.0,10073000000.0,3033000000.0
Change In Cash,5967000000.0,4237000000.0,10317000000.0,1922000000.0
Effect Of Exchange Rate,618000000.0,70000000.0,-351000000.0,713000000.0
Total Cash From Operating Activities,66064000000.0,38514000000.0,30723000000.0,18365000000.0
Depreciation,25251000000.0,21789000000.0,15341000000.0,11478000000.0
Change To Inventory,-2849000000.0,-3278000000.0,-1314000000.0,-3583000000.0
Change To Account Receivables,-8169000000.0,-7681000000.0,-4615000000.0,-4780000000.0
Change To Netincome,6001000000.0,7575000000.0,6352000000.0,4096000000.0
Capital Expenditures,-40140000000.0,-16861000000.0,-13427000000.0,-11955000000.0
Other Cashflows From Investing Activities,nan,nan,2104000000.0,1897000000.0

In [138]:
msft.earnings

           Revenue     Earnings
Year
2017  177866000000   3033000000
2018  232887000000  10073000000
2019  280522000000  11588000000
2020  386064000000  21331000000

# YahooFinancials lisäosalla

* [Linkki](https://github.com/JECSand/yahoofinancials)

In [29]:
from yahoofinancials import YahooFinancials

ticker = 'CAT'
yahoo_financials = YahooFinancials(ticker)

balance_sheet_data_qt = yahoo_financials.get_financial_stmts('annual', 'balance')
income_statement_data_qt = yahoo_financials.get_financial_stmts('annual', 'income')
all_statement_data_qt =  yahoo_financials.get_financial_stmts('annual', ['income', 'cash', 'balance'])
apple_earnings_data = yahoo_financials.get_stock_earnings_data()
apple_net_income = yahoo_financials.get_net_income()
historical_stock_prices = yahoo_financials.get_historical_price_data('2008-09-15', '2018-09-15', 'weekly')

yahoo_financials.get_prev_close_price()

balance_sheet_data_qt

{'balanceSheetHistory': {'CAT': [{'2020-12-31': {'intangibleAssets': 1308000000,
     'totalLiab': 62946000000,
     'totalStockholderEquity': 15331000000,
     'minorityInterest': 47000000,
     'otherCurrentLiab': 3561000000,
     'totalAssets': 78324000000,
     'commonStock': 6230000000,
     'otherCurrentAssets': 133000000,
     'retainedEarnings': 35167000000,
     'otherLiab': 10773000000,
     'goodWill': 6394000000,
     'treasuryStock': -26066000000,
     'otherAssets': 4180000000,
     'cash': 8822000000,
     'totalCurrentLiabilities': 25717000000,
     'deferredLongTermAssetCharges': 1358000000,
     'shortLongTermDebt': 1420000000,
     'otherStockholderEquity': -888000000,
     'propertyPlantEquipment': 8912000000,
     'totalCurrentAssets': 39464000000,
     'longTermInvestments': 1687000000,
     'netTangibleAssets': 7629000000,
     'netReceivables': 7178000000,
     'longTermDebt': 9646000000,
     'inventory': 11402000000,
     'accountsPayable': 6128000000}},
   {'2019-12-31': {'intangibleAssets': 1565000000,
     'totalLiab': 63824000000,
     'totalStockholderEquity': 14588000000,
     'minorityInterest': 41000000,
     'otherCurrentLiab': 3757000000,
     'totalAssets': 78453000000,
     'commonStock': 5935000000,
     'otherCurrentAssets': 31000000,
     'retainedEarnings': 34437000000,
     'otherLiab': 10461000000,
     'goodWill': 6196000000,
     'treasuryStock': -25784000000,
     'otherAssets': 3932000000,
     'cash': 7299000000,
     'totalCurrentLiabilities': 26621000000,
     'deferredLongTermAssetCharges': 1324000000,
     'shortLongTermDebt': 16000000,
     'otherStockholderEquity': -1567000000,
     'propertyPlantEquipment': 9230000000,
     'totalCurrentAssets': 39193000000,
     'longTermInvestments': 1365000000,
     'netTangibleAssets': 6827000000,
     'netReceivables': 8484000000,
     'longTermDebt': 9013000000,
     'inventory': 11266000000,
     'accountsPayable': 5957000000}},
   {'2018-12-31': {'intangibleAssets': 1897000000,
     'totalLiab': 64429000000,
     'totalStockholderEquity': 14039000000,
     'minorityInterest': 41000000,
     'otherCurrentLiab': 3735000000,
     'totalAssets': 78509000000,
     'commonStock': 5827000000,
     'otherCurrentAssets': 52000000,
     'retainedEarnings': 30427000000,
     'otherLiab': 11211000000,
     'goodWill': 6217000000,
     'treasuryStock': -22215000000,
     'otherAssets': 3443000000,
     'cash': 6968000000,
     'totalCurrentLiabilities': 28218000000,
     'deferredLongTermAssetCharges': 1363000000,
     'shortLongTermDebt': 10000000,
     'otherStockholderEquity': -1684000000,
     'propertyPlantEquipment': 9085000000,
     'totalCurrentAssets': 38603000000,
     'netTangibleAssets': 5925000000,
     'netReceivables': 8714000000,
     'longTermDebt': 8005000000,
     'inventory': 11529000000,
     'accountsPayable': 7051000000}},
   {'2017-12-31': {'intangibleAssets': 2106000000,
     'totalLiab': 63196000000,
     'totalStockholderEquity': 13697000000,
     'minorityInterest': 69000000,
     'otherCurrentLiab': 3657000000,
     'totalAssets': 76962000000,
     'commonStock': 5593000000,
     'otherCurrentAssets': 242000000,
     'retainedEarnings': 26301000000,
     'otherLiab': 12418000000,
     'goodWill': 6183000000,
     'treasuryStock': -18197000000,
     'otherAssets': 3495000000,
     'cash': 7381000000,
     'totalCurrentLiabilities': 26931000000,
     'deferredLongTermAssetCharges': 1569000000,
     'shortLongTermDebt': 6000000,
     'otherStockholderEquity': -1192000000,
     'propertyPlantEquipment': 9823000000,
     'totalCurrentAssets': 36244000000,
     'netTangibleAssets': 5386000000,
     'netReceivables': 7376000000,
     'longTermDebt': 7492000000,
     'inventory': 10018000000,
     'accountsPayable': 6487000000}}]}}

In [ ]:
print("income statement")
print(income_statement_data_qt)

income statement
{'incomeStatementHistory': {'ABB': [{'2020-12-31': {'researchDevelopment': 1113000000, 'effectOfAccountingCharges': None, 'incomeBeforeTax': 841000000, 'minorityInterest': 314000000, 'netIncome': 5146000000, 'sellingGeneralAdministrative': 5144000000, 'grossProfit': 8011000000, 'ebit': 1881000000, 'operatingIncome': 1881000000, 'otherOperatingExpenses': -127000000, 'interestExpense': -448000000, 'extraordinaryItems': None, 'nonRecurring': None, 'otherItems': None, 'incomeTaxExpense': 496000000, 'totalRevenue': 26134000000, 'totalOperatingExpenses': 24253000000, 'costOfRevenue': 18123000000, 'totalOtherIncomeExpenseNet': -1040000000, 'discontinuedOperations': 4860000000, 'netIncomeFromContinuingOps': 345000000, 'netIncomeApplicableToCommonShares': 5146000000}}, {'2019-12-31': {'researchDevelopment': 1197000000, 'effectOfAccountingCharges': None, 'incomeBeforeTax': 1862000000, 'minorityInterest': 454000000, 'netIncome': 1439000000, 'sellingGeneralAdministrative': 5135000000, 'grossProfit': 8960000000, 'ebit': 2650000000, 'operatingIncome': 2650000000, 'otherOperatingExpenses': -22000000, 'interestExpense': -93000000, 'extraordinaryItems': None, 'nonRecurring': None, 'otherItems': None, 'incomeTaxExpense': 772000000, 'totalRevenue': 27978000000, 'totalOperatingExpenses': 25328000000, 'costOfRevenue': 19018000000, 'totalOtherIncomeExpenseNet': -788000000, 'discontinuedOperations': 438000000, 'netIncomeFromContinuingOps': 1090000000, 'netIncomeApplicableToCommonShares': 1439000000}}, {'2018-12-31': {'researchDevelopment': 1142000000, 'effectOfAccountingCharges': None, 'incomeBeforeTax': 2119000000, 'minorityInterest': 582000000, 'netIncome': 2173000000, 'sellingGeneralAdministrative': 5137000000, 'grossProfit': 8603000000, 'ebit': 2370000000, 'operatingIncome': 2370000000, 'otherOperatingExpenses': -46000000, 'interestExpense': -305000000, 'extraordinaryItems': None, 'nonRecurring': None, 'otherItems': None, 'incomeTaxExpense': 544000000, 'totalRevenue': 27662000000, 'totalOperatingExpenses': 25292000000, 'costOfRevenue': 19059000000, 'totalOtherIncomeExpenseNet': -251000000, 'discontinuedOperations': 723000000, 'netIncomeFromContinuingOps': 1575000000, 'netIncomeApplicableToCommonShares': 2173000000}}, {'2017-12-31': {'researchDevelopment': 1018000000, 'effectOfAccountingCharges': None, 'incomeBeforeTax': 2102000000, 'minorityInterest': 530000000, 'netIncome': 2213000000, 'sellingGeneralAdministrative': 4757000000, 'grossProfit': 7918000000, 'ebit': 2143000000, 'operatingIncome': 2143000000, 'otherOperatingExpenses': -46000000, 'interestExpense': -254000000, 'extraordinaryItems': None, 'nonRecurring': None, 'otherItems': None, 'incomeTaxExpense': 583000000, 'totalRevenue': 25196000000, 'totalOperatingExpenses': 23053000000, 'costOfRevenue': 17278000000, 'totalOtherIncomeExpenseNet': -41000000, 'discontinuedOperations': 846000000, 'netIncomeFromContinuingOps': 1519000000, 'netIncomeApplicableToCommonShares': 2213000000}}]}}

In [ ]:
balance_sheet_data_qt

{'balanceSheetHistory': {'ABB': [{'2020-12-31': {'intangibleAssets': 2077000000,
     'capitalSurplus': 83000000,
     'totalLiab': 25089000000,
     'totalStockholderEquity': 15685000000,
     'minorityInterest': 314000000,
     'otherCurrentLiab': 6313000000,
     'totalAssets': 41088000000,
     'commonStock': 188000000,
     'otherCurrentAssets': 1357000000,
     'retainedEarnings': 22946000000,
     'otherLiab': 4114000000,
     'goodWill': 10850000000,
     'treasuryStock': -7532000000,
     'otherAssets': 1930000000,
     'cash': 3278000000,
     'totalCurrentLiabilities': 15416000000,
     'deferredLongTermAssetCharges': 843000000,
     'shortLongTermDebt': 1115000000,
     'otherStockholderEquity': -4002000000,
     'propertyPlantEquipment': 5143000000,
     'totalCurrentAssets': 19226000000,
     'longTermInvestments': 1862000000,
     'netTangibleAssets': 2758000000,
     'shortTermInvestments': 2108000000,
     'netReceivables': 7805000000,
     'longTermDebt': 4668000000,
     'inventory': 4469000000,
     'accountsPayable': 4571000000}},
   {'2019-12-31': {'intangibleAssets': 2252000000,
     'capitalSurplus': 73000000,
     'totalLiab': 32128000000,
     'totalStockholderEquity': 13526000000,
     'minorityInterest': 454000000,
     'otherCurrentLiab': 10516000000,
     'totalAssets': 46108000000,
     'commonStock': 188000000,
     'otherCurrentAssets': 10550000000,
     'retainedEarnings': 19640000000,
     'otherLiab': 4373000000,
     'goodWill': 10825000000,
     'treasuryStock': -6375000000,
     'otherAssets': 1502000000,
     'cash': 3508000000,
     'totalCurrentLiabilities': 20266000000,
     'deferredLongTermAssetCharges': 910000000,
     'shortLongTermDebt': 1432000000,
     'otherStockholderEquity': -5590000000,
     'propertyPlantEquipment': 4966000000,
     'totalCurrentAssets': 26458000000,
     'longTermInvestments': 105000000,
     'netTangibleAssets': 449000000,
     'shortTermInvestments': 566000000,
     'netReceivables': 7459000000,
     'longTermDebt': 6618000000,
     'inventory': 4184000000,
     'accountsPayable': 4353000000}},
   {'2018-12-31': {'intangibleAssets': 2607000000,
     'capitalSurplus': 56000000,
     'totalLiab': 29907000000,
     'totalStockholderEquity': 13952000000,
     'minorityInterest': 582000000,
     'otherCurrentLiab': 9091000000,
     'totalAssets': 44441000000,
     'commonStock': 188000000,
     'otherCurrentAssets': 5780000000,
     'retainedEarnings': 19839000000,
     'otherLiab': 4872000000,
     'goodWill': 10764000000,
     'treasuryStock': -6131000000,
     'otherAssets': 4950000000,
     'cash': 3445000000,
     'totalCurrentLiabilities': 18447000000,
     'deferredLongTermAssetCharges': 1006000000,
     'shortLongTermDebt': 1447000000,
     'otherStockholderEquity': -5311000000,
     'propertyPlantEquipment': 4133000000,
     'totalCurrentAssets': 21865000000,
     'longTermInvestments': 122000000,
     'netTangibleAssets': 581000000,
     'shortTermInvestments': 712000000,
     'netReceivables': 7468000000,
     'longTermDebt': 6458000000,
     'inventory': 4284000000,
     'accountsPayable': 4424000000}},
   {'2017-12-31': {'intangibleAssets': 2425000000,
     'capitalSurplus': 29000000,
     'totalLiab': 28109000000,
     'totalStockholderEquity': 14819000000,
     'minorityInterest': 530000000,
     'otherCurrentLiab': 9419000000,
     'totalAssets': 43458000000,
     'commonStock': 188000000,
     'otherCurrentAssets': 5628000000,
     'retainedEarnings': 19594000000,
     'otherLiab': 4954000000,
     'goodWill': 9536000000,
     'treasuryStock': -4992000000,
     'otherAssets': 5445000000,
     'cash': 4526000000,
     'totalCurrentLiabilities': 16469000000,
     'deferredLongTermAssetCharges': 1212000000,
     'shortLongTermDebt': 379000000,
     'otherStockholderEquity': -4345000000,
     'propertyPlantEquipment': 3804000000,
     'totalCurrentAssets': 22135000000,
     'longTermInvestments': 113000000,
     'netTangibleAssets': 2858000000,
     'shortTermInvestments': 1083000000,
     'netReceivables': 7002000000,
     'longTermDebt': 6571000000,
     'inventory': 3737000000,
     'accountsPayable': 3736000000}}]}}

In [154]:
from yahoofinancials import YahooFinancials

ticker = 'AMZN'
yahoo_financials = YahooFinancials(ticker)


import yfinance as yf

ticker_yfinance = yf.Ticker(ticker)

# Hakee osakkeiden lukumäärän
shares_outstanding = ticker_yfinance.info['sharesOutstanding']

# Hakee hinnan
prev_close = yahoo_financials.get_prev_close_price()

market_value_of_equity = shares_outstanding*prev_close
print("mkt eqt: ", market_value_of_equity)

#total_liabilities =

mkt eqt:  1693351294080.96

In [153]:
ticker_yfinance.info['sharesOutstanding']

506440992

In [135]:
income_statement_data_qt

{'incomeStatementHistory': {'AMZN': [{'2020-12-31': {'researchDevelopment': 42740000000,
     'effectOfAccountingCharges': None,
     'incomeBeforeTax': 24194000000,
     'minorityInterest': None,
     'netIncome': 21331000000,
     'sellingGeneralAdministrative': 87193000000,
     'grossProfit': 152757000000,
     'ebit': 22899000000,
     'operatingIncome': 22899000000,
     'otherOperatingExpenses': -75000000,
     'interestExpense': -1647000000,
     'extraordinaryItems': None,
     'nonRecurring': None,
     'otherItems': None,
     'incomeTaxExpense': 2863000000,
     'totalRevenue': 386064000000,
     'totalOperatingExpenses': 363165000000,
     'costOfRevenue': 233307000000,
     'totalOtherIncomeExpenseNet': 1295000000,
     'discontinuedOperations': None,
     'netIncomeFromContinuingOps': 21331000000,
     'netIncomeApplicableToCommonShares': 21331000000}},
   {'2019-12-31': {'researchDevelopment': 35931000000,
     'effectOfAccountingCharges': None,
     'incomeBeforeTax': 13962000000,
     'minorityInterest': None,
     'netIncome': 11588000000,
     'sellingGeneralAdministrative': 64313000000,
     'grossProfit': 114986000000,
     'ebit': 14404000000,
     'operatingIncome': 14404000000,
     'otherOperatingExpenses': 338000000,
     'interestExpense': -1600000000,
     'extraordinaryItems': None,
     'nonRecurring': None,
     'otherItems': None,
     'incomeTaxExpense': 2374000000,
     'totalRevenue': 280522000000,
     'totalOperatingExpenses': 266118000000,
     'costOfRevenue': 165536000000,
     'totalOtherIncomeExpenseNet': -442000000,
     'discontinuedOperations': None,
     'netIncomeFromContinuingOps': 11588000000,
     'netIncomeApplicableToCommonShares': 11588000000}},
   {'2018-12-31': {'researchDevelopment': 28837000000,
     'effectOfAccountingCharges': None,
     'incomeBeforeTax': 11270000000,
     'minorityInterest': None,
     'netIncome': 10073000000,
     'sellingGeneralAdministrative': 52177000000,
     'grossProfit': 93731000000,
     'ebit': 12421000000,
     'operatingIncome': 12421000000,
     'otherOperatingExpenses': 296000000,
     'interestExpense': -1417000000,
     'extraordinaryItems': None,
     'nonRecurring': None,
     'otherItems': None,
     'incomeTaxExpense': 1197000000,
     'totalRevenue': 232887000000,
     'totalOperatingExpenses': 220466000000,
     'costOfRevenue': 139156000000,
     'totalOtherIncomeExpenseNet': -1151000000,
     'discontinuedOperations': None,
     'netIncomeFromContinuingOps': 10073000000,
     'netIncomeApplicableToCommonShares': 10073000000}},
   {'2017-12-31': {'researchDevelopment': 22620000000,
     'effectOfAccountingCharges': None,
     'incomeBeforeTax': 3802000000,
     'minorityInterest': None,
     'netIncome': 3033000000,
     'sellingGeneralAdministrative': 38992000000,
     'grossProfit': 65932000000,
     'ebit': 4106000000,
     'operatingIncome': 4106000000,
     'otherOperatingExpenses': 214000000,
     'interestExpense': -848000000,
     'extraordinaryItems': None,
     'nonRecurring': None,
     'otherItems': None,
     'incomeTaxExpense': 769000000,
     'totalRevenue': 177866000000,
     'totalOperatingExpenses': 173760000000,
     'costOfRevenue': 111934000000,
     'totalOtherIncomeExpenseNet': -304000000,
     'discontinuedOperations': None,
     'netIncomeFromContinuingOps': 3033000000,
     'netIncomeApplicableToCommonShares': 3033000000}}]}}

In [128]:
balance_sheet_data_qt

{'balanceSheetHistoryQuarterly': {'AAPL': [{'2021-06-26': {'totalLiab': 265560000000,
     'totalStockholderEquity': 64280000000,
     'otherCurrentLiab': 51306000000,
     'totalAssets': 329840000000,
     'commonStock': 54989000000,
     'otherCurrentAssets': 13641000000,
     'retainedEarnings': 9233000000,
     'otherLiab': 38354000000,
     'treasuryStock': 58000000,
     'otherAssets': 44854000000,
     'cash': 34050000000,
     'totalCurrentLiabilities': 107754000000,
     'shortLongTermDebt': 8039000000,
     'otherStockholderEquity': 58000000,
     'propertyPlantEquipment': 38615000000,
     'totalCurrentAssets': 114423000000,
     'longTermInvestments': 131948000000,
     'netTangibleAssets': 64280000000,
     'shortTermInvestments': 27646000000,
     'netReceivables': 33908000000,
     'longTermDebt': 105752000000,
     'inventory': 5178000000,
     'accountsPayable': 40409000000}},
   {'2021-03-27': {'totalLiab': 267980000000,
     'totalStockholderEquity': 69178000000,
     'otherCurrentLiab': 53255000000,
     'totalAssets': 337158000000,
     'commonStock': 54203000000,
     'otherCurrentAssets': 13376000000,
     'retainedEarnings': 15261000000,
     'otherLiab': 39853000000,
     'treasuryStock': -286000000,
     'otherAssets': 43339000000,
     'cash': 38466000000,
     'totalCurrentLiabilities': 106385000000,
     'shortLongTermDebt': 8003000000,
     'otherStockholderEquity': -286000000,
     'propertyPlantEquipment': 37815000000,
     'totalCurrentAssets': 121465000000,
     'longTermInvestments': 134539000000,
     'netTangibleAssets': 69178000000,
     'shortTermInvestments': 31368000000,
     'netReceivables': 33036000000,
     'longTermDebt': 108642000000,
     'inventory': 5219000000,
     'accountsPayable': 40127000000}},
   {'2020-12-26': {'totalLiab': 287830000000,
     'totalStockholderEquity': 66224000000,
     'otherCurrentLiab': 55899000000,
     'totalAssets': 354054000000,
     'commonStock': 51744000000,
     'otherCurrentAssets': 13687000000,
     'retainedEarnings': 14301000000,
     'otherLiab': 43042000000,
     'treasuryStock': 179000000,
     'otherAssets': 43270000000,
     'cash': 36010000000,
     'totalCurrentLiabilities': 132507000000,
     'shortLongTermDebt': 7762000000,
     'otherStockholderEquity': 179000000,
     'propertyPlantEquipment': 37933000000,
     'totalCurrentAssets': 154106000000,
     'longTermInvestments': 118745000000,
     'netTangibleAssets': 66224000000,
     'shortTermInvestments': 40816000000,
     'netReceivables': 58620000000,
     'longTermDebt': 99281000000,
     'inventory': 4973000000,
     'accountsPayable': 63846000000}},
   {'2020-09-26': {'totalLiab': 258549000000,
     'totalStockholderEquity': 65339000000,
     'otherCurrentLiab': 47867000000,
     'totalAssets': 323888000000,
     'commonStock': 50779000000,
     'otherCurrentAssets': 11264000000,
     'retainedEarnings': 14966000000,
     'otherLiab': 46108000000,
     'treasuryStock': -406000000,
     'otherAssets': 33952000000,
     'cash': 38016000000,
     'totalCurrentLiabilities': 105392000000,
     'shortLongTermDebt': 8773000000,
     'otherStockholderEquity': -406000000,
     'propertyPlantEquipment': 45336000000,
     'totalCurrentAssets': 143713000000,
     'longTermInvestments': 100887000000,
     'netTangibleAssets': 65339000000,
     'shortTermInvestments': 52927000000,
     'netReceivables': 37445000000,
     'longTermDebt': 98667000000,
     'inventory': 4061000000,
     'accountsPayable': 42296000000}}]}}

In [130]:
print(all_statement_data_qt)

{'incomeStatementHistoryQuarterly': {'AAPL': [{'2021-06-26': {'researchDevelopment': 5717000000, 'effectOfAccountingCharges': None, 'incomeBeforeTax': 24369000000, 'minorityInterest': None, 'netIncome': 21744000000, 'sellingGeneralAdministrative': 5412000000, 'grossProfit': 35255000000, 'ebit': 24126000000, 'operatingIncome': 24126000000, 'otherOperatingExpenses': None, 'interestExpense': -665000000, 'extraordinaryItems': None, 'nonRecurring': None, 'otherItems': None, 'incomeTaxExpense': 2625000000, 'totalRevenue': 81434000000, 'totalOperatingExpenses': 57308000000, 'costOfRevenue': 46179000000, 'totalOtherIncomeExpenseNet': 243000000, 'discontinuedOperations': None, 'netIncomeFromContinuingOps': 21744000000, 'netIncomeApplicableToCommonShares': 21744000000}}, {'2021-03-27': {'researchDevelopment': 5262000000, 'effectOfAccountingCharges': None, 'incomeBeforeTax': 28011000000, 'minorityInterest': None, 'netIncome': 23630000000, 'sellingGeneralAdministrative': 5314000000, 'grossProfit': 38079000000, 'ebit': 27503000000, 'operatingIncome': 27503000000, 'otherOperatingExpenses': None, 'interestExpense': -670000000, 'extraordinaryItems': None, 'nonRecurring': None, 'otherItems': None, 'incomeTaxExpense': 4381000000, 'totalRevenue': 89584000000, 'totalOperatingExpenses': 62081000000, 'costOfRevenue': 51505000000, 'totalOtherIncomeExpenseNet': 508000000, 'discontinuedOperations': None, 'netIncomeFromContinuingOps': 23630000000, 'netIncomeApplicableToCommonShares': 23630000000}}, {'2020-12-26': {'researchDevelopment': 5163000000, 'effectOfAccountingCharges': None, 'incomeBeforeTax': 33579000000, 'minorityInterest': None, 'netIncome': 28755000000, 'sellingGeneralAdministrative': 5631000000, 'grossProfit': 44328000000, 'ebit': 33534000000, 'operatingIncome': 33534000000, 'otherOperatingExpenses': None, 'interestExpense': -638000000, 'extraordinaryItems': None, 'nonRecurring': None, 'otherItems': None, 'incomeTaxExpense': 4824000000, 'totalRevenue': 111439000000, 'totalOperatingExpenses': 77905000000, 'costOfRevenue': 67111000000, 'totalOtherIncomeExpenseNet': 45000000, 'discontinuedOperations': None, 'netIncomeFromContinuingOps': 28755000000, 'netIncomeApplicableToCommonShares': 28755000000}}, {'2020-09-26': {'researchDevelopment': 4978000000, 'effectOfAccountingCharges': None, 'incomeBeforeTax': 14901000000, 'minorityInterest': None, 'netIncome': 12673000000, 'sellingGeneralAdministrative': 4936000000, 'grossProfit': 24689000000, 'ebit': 14775000000, 'operatingIncome': 14775000000, 'otherOperatingExpenses': None, 'interestExpense': -634000000, 'extraordinaryItems': None, 'nonRecurring': None, 'otherItems': None, 'incomeTaxExpense': 2228000000, 'totalRevenue': 64698000000, 'totalOperatingExpenses': 49923000000, 'costOfRevenue': 40009000000, 'totalOtherIncomeExpenseNet': 126000000, 'discontinuedOperations': None, 'netIncomeFromContinuingOps': 12673000000, 'netIncomeApplicableToCommonShares': 12673000000}}]}, 'cashflowStatementHistoryQuarterly': {'AAPL': [{'2021-06-26': {'investments': 5747000000, 'changeToLiabilities': 307000000, 'totalCashflowsFromInvestingActivities': 3572000000, 'totalCashFromFinancingActivities': -29396000000, 'changeToOperatingActivities': -6048000000, 'netIncome': 21744000000, 'changeInCash': -4730000000, 'repurchaseOfStock': -25595000000, 'totalCashFromOperatingActivities': 21094000000, 'depreciation': 2832000000, 'otherCashflowsFromInvestingActivities': -78000000, 'dividendsPaid': -3767000000, 'changeToInventory': 13000000, 'changeToAccountReceivables': 1031000000, 'otherCashflowsFromFinancingActivities': -34000000, 'changeToNetincome': 1215000000, 'capitalExpenditures': -2093000000}}, {'2021-03-27': {'investments': -7895000000, 'changeToLiabilities': -23366000000, 'totalCashflowsFromInvestingActivities': -10368000000, 'netBorrowings': 10423000000, 'totalCashFromFinancingActivities': -11326000000, 'changeToOperatingActivities': 11265000000, 'issuanceOfStock': 561000000, 'netIncome': 23630000000, 'changeInCash': 2287000000, 'repurchaseOfStock': -18847000000, 'totalCashFromOperatingActivities': 23981000000, 'depreciation': 2797000000, 'otherCashflowsFromInvestingActivities': -204000000, 'dividendsPaid': -3447000000, 'changeToInventory': -276000000, 'changeToAccountReceivables': 8598000000, 'otherCashflowsFromFinancingActivities': -16000000, 'changeToNetincome': 1333000000, 'capitalExpenditures': -2269000000}}, {'2020-12-26': {'investments': -5279000000, 'changeToLiabilities': 23011000000, 'totalCashflowsFromInvestingActivities': -8584000000, 'netBorrowings': -978000000, 'totalCashFromFinancingActivities': -32249000000, 'changeToOperatingActivities': -5761000000, 'issuanceOfStock': 561000000, 'netIncome': 28755000000, 'changeInCash': -2070000000, 'repurchaseOfStock': -27636000000, 'totalCashFromOperatingActivities': 38763000000, 'depreciation': 2666000000, 'otherCashflowsFromInvestingActivities': 204000000, 'dividendsPaid': -3613000000, 'changeToInventory': -950000000, 'changeToAccountReceivables': -10945000000, 'otherCashflowsFromFinancingActivities': -22000000, 'changeToNetincome': 1987000000, 'capitalExpenditures': -3500000000}}, {'2020-09-26': {'investments': 7468000000, 'changeToLiabilities': 7157000000, 'totalCashflowsFromInvestingActivities': 5531000000, 'netBorrowings': -703000000, 'totalCashFromFinancingActivities': -21357000000, 'changeToOperatingActivities': -4911000000, 'issuanceOfStock': 450000000, 'netIncome': 12673000000, 'changeInCash': 4750000000, 'repurchaseOfStock': -17587000000, 'totalCashFromOperatingActivities': 20576000000, 'depreciation': 2702000000, 'otherCashflowsFromInvestingActivities': -102000000, 'dividendsPaid': -3511000000, 'changeToInventory': -137000000, 'changeToAccountReceivables': 1768000000, 'otherCashflowsFromFinancingActivities': -6000000, 'changeToNetincome': 1324000000, 'capitalExpenditures': -1784000000}}]}, 'balanceSheetHistoryQuarterly': {'AAPL': [{'2021-06-26': {'totalLiab': 265560000000, 'totalStockholderEquity': 64280000000, 'otherCurrentLiab': 51306000000, 'totalAssets': 329840000000, 'commonStock': 54989000000, 'otherCurrentAssets': 13641000000, 'retainedEarnings': 9233000000, 'otherLiab': 38354000000, 'treasuryStock': 58000000, 'otherAssets': 44854000000, 'cash': 34050000000, 'totalCurrentLiabilities': 107754000000, 'shortLongTermDebt': 8039000000, 'otherStockholderEquity': 58000000, 'propertyPlantEquipment': 38615000000, 'totalCurrentAssets': 114423000000, 'longTermInvestments': 131948000000, 'netTangibleAssets': 64280000000, 'shortTermInvestments': 27646000000, 'netReceivables': 33908000000, 'longTermDebt': 105752000000, 'inventory': 5178000000, 'accountsPayable': 40409000000}}, {'2021-03-27': {'totalLiab': 267980000000, 'totalStockholderEquity': 69178000000, 'otherCurrentLiab': 53255000000, 'totalAssets': 337158000000, 'commonStock': 54203000000, 'otherCurrentAssets': 13376000000, 'retainedEarnings': 15261000000, 'otherLiab': 39853000000, 'treasuryStock': -286000000, 'otherAssets': 43339000000, 'cash': 38466000000, 'totalCurrentLiabilities': 106385000000, 'shortLongTermDebt': 8003000000, 'otherStockholderEquity': -286000000, 'propertyPlantEquipment': 37815000000, 'totalCurrentAssets': 121465000000, 'longTermInvestments': 134539000000, 'netTangibleAssets': 69178000000, 'shortTermInvestments': 31368000000, 'netReceivables': 33036000000, 'longTermDebt': 108642000000, 'inventory': 5219000000, 'accountsPayable': 40127000000}}, {'2020-12-26': {'totalLiab': 287830000000, 'totalStockholderEquity': 66224000000, 'otherCurrentLiab': 55899000000, 'totalAssets': 354054000000, 'commonStock': 51744000000, 'otherCurrentAssets': 13687000000, 'retainedEarnings': 14301000000, 'otherLiab': 43042000000, 'treasuryStock': 179000000, 'otherAssets': 43270000000, 'cash': 36010000000, 'totalCurrentLiabilities': 132507000000, 'shortLongTermDebt': 7762000000, 'otherStockholderEquity': 179000000, 'propertyPlantEquipment': 37933000000, 'totalCurrentAssets': 154106000000, 'longTermInvestments': 118745000000, 'netTangibleAssets': 66224000000, 'shortTermInvestments': 40816000000, 'netReceivables': 58620000000, 'longTermDebt': 99281000000, 'inventory': 4973000000, 'accountsPayable': 63846000000}}, {'2020-09-26': {'totalLiab': 258549000000, 'totalStockholderEquity': 65339000000, 'otherCurrentLiab': 47867000000, 'totalAssets': 323888000000, 'commonStock': 50779000000, 'otherCurrentAssets': 11264000000, 'retainedEarnings': 14966000000, 'otherLiab': 46108000000, 'treasuryStock': -406000000, 'otherAssets': 33952000000, 'cash': 38016000000, 'totalCurrentLiabilities': 105392000000, 'shortLongTermDebt': 8773000000, 'otherStockholderEquity': -406000000, 'propertyPlantEquipment': 45336000000, 'totalCurrentAssets': 143713000000, 'longTermInvestments': 100887000000, 'netTangibleAssets': 65339000000, 'shortTermInvestments': 52927000000, 'netReceivables': 37445000000, 'longTermDebt': 98667000000, 'inventory': 4061000000, 'accountsPayable': 42296000000}}]}}

# Calculating Ponsse's beta using different indices

In [39]:
#!pip install pandas-datareader

In [61]:
import numpy as np
import pandas as pd
from pandas_datareader import data

tickers = ["^OMXHCAPGI", 'PON1V.HE']

In [62]:
#import yfinance as yf
tickers = ["^OMXHCAPGI", "PON1V.HE"]
#omxh = yf.Ticker(tickers)
#hist = omxh.history(period="5y", interval='1d')

from pandas_datareader import data

beta_data = data.DataReader(tickers, 'yahoo', start='2016-11-25', end='2021-11-25')

In [63]:
beta_data = beta_data['Adj Close']

In [72]:
beta_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1258 entries, 2016-11-25 to 2021-11-25
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ^OMXHCAPGI  1248 non-null   float64
 1   PON1V.HE    1256 non-null   float64
dtypes: float64(2)
memory usage: 29.5 KB

## Data contains some null/NaN-values.

As an easy fix, let's just drop the rows with null values. That shouldn't affect our results anyway

In [73]:
beta_data = beta_data.dropna()

In [74]:
beta_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1246 entries, 2016-11-25 to 2021-11-25
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ^OMXHCAPGI  1246 non-null   float64
 1   PON1V.HE    1246 non-null   float64
dtypes: float64(2)
memory usage: 29.2 KB

# Shift

In [75]:
import numpy as np

In [76]:
log_returns = np.log(beta_data/beta_data.shift())

# Beta calculation

In [77]:
cov = log_returns.cov()
# Variance for index
var = log_returns['^OMXHCAPGI'].var()
cov.loc['PON1V.HE', '^OMXHCAPGI']/var

0.7351913045364821

In [78]:
#!pip install -U scikit-learn

# Double checking result by calculating Beta value from Linear Regression

In [79]:
from sklearn.linear_model import LinearRegression

In [80]:
X = log_returns['^OMXHCAPGI'].iloc[1:].to_numpy().reshape(-1, 1)
Y = log_returns['PON1V.HE'].iloc[1:].to_numpy().reshape(-1, 1)
 
lin_regr = LinearRegression()
lin_regr.fit(X, Y)
 
lin_regr.coef_[0, 0]

0.735191304536483

### Looks like there's a tiny difference in the values, but not noticeable enough to warrant doing anything

* Normal beta calculation result: 0.7351913045364821
* Linear regression beta  result: 0.735191304536483

In [33]:
# pd.set_option("max_columns", None) # show all cols
# pd.set_option('max_colwidth', None) # show full width of showing cols
# pd.set_option("expand_frame_repr", False) # print cols side by side as it's supposed to be

In [31]:
hist

                    Open          High           Low         Close  Volume  Dividends  Stock Splits
Date
2016-11-25  15104.799805  15152.419922  15064.080078  15133.219727       0          0             0
2016-11-28  15117.030273  15124.459961  14986.410156  14998.450195       0          0             0
2016-11-29  14993.980469  15021.820312  14917.059570  14965.709961       0          0             0
2016-11-30  14984.070312  15102.809570  14984.070312  15034.339844       0          0             0
2016-12-01  15031.389648  15126.400391  14983.259766  15005.419922       0          0             0
...                  ...           ...           ...           ...     ...        ...           ...
2021-11-19  29597.500000  29679.789062  29323.830078  29462.140625       0          0             0
2021-11-22  29493.259766  29615.390625  29399.130859  29521.640625       0          0             0
2021-11-23  29350.070312  29359.449219  29066.740234  29079.740234       0          0             0
2021-11-24  29049.859375  29262.609375  28918.119141  29033.259766       0          0             0
2021-11-25  29073.828125  29300.970703  29073.115234  29300.970703       0          0             0

[1247 rows x 7 columns]